#!/usr/bin/env python3
"""把 .NET 侧物理表名/列名从 snake_case 改成 camelCase 的一次性工具。

背景：PostgreSQL 里的物理名一直沿用 Go/GORM 的 snake_case（user_id），
.NET 实体是 PascalCase（UserID）。Dapper 靠命名匹配兜底，但手写 SQL 一旦
漏写别名就会静默读成默认值。本工具产出改名计划，供迁移与代码改写使用：

    python scripts/rename-schema-identifiers.py --report
    python scripts/rename-schema-identifiers.py --plan-cs <输出.cs>
    python scripts/rename-schema-identifiers.py --rename-sql <输出.sql>

注意：stdout 只输出 ASCII，避免 Windows 下 cp936 编码把中文报告吞掉。
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# 命名规则与账本例外由 schema_identifiers 统一提供，避免与生成器漂移。
from schema_identifiers import (  # noqa: E402
    LEDGER_COLUMNS,
    LEDGER_TABLE,
    camel,
    physical_column,
    physical_table,
)

ROOT = Path(__file__).resolve().parent.parent
DUMP = ROOT / "schema-dump.json"
CATALOG = ROOT / "src" / "OpenAICanvas.Persistence" / "SchemaMigrationCatalog.cs"


def catalog_contract_literals() -> set[str]:
    """迁移目录里作为契约的字符串：各版本的迁移名与校验和（含 sha256 常量）。

    这些值必须与已发布记录逐字一致，不随物理标识符改名。其中 <c>agent_profiles</c>
    同时又是表名，是最容易被误伤的一个。
    """
    if not CATALOG.exists():
        return set()
    text = CATALOG.read_text(encoding="utf-8")
    names = set(re.findall(r'Name\s*=\s*"([^"]+)"', text))
    checksums = set(re.findall(r'"(sha256:[^"]+)"', text))
    return names | checksums


_PROTECTED_CACHE: set[str] | None = None


def _protected_literals() -> set[str]:
    global _PROTECTED_CACHE
    if _PROTECTED_CACHE is None:
        _PROTECTED_CACHE = catalog_contract_literals()
    return _PROTECTED_CACHE


def is_sql_source(path: Path) -> bool:
    """只改写真正承载 SQL 的文件，避免把上游协议字段名、日志键一起改掉。"""
    parts = path.parts
    if "OpenAICanvas.Persistence" in parts and path.parent.name == "Repositories":
        return True
    if "OpenAICanvas.Tools" in parts and path.parent.name == "Commands":
        return True
    return path.relative_to(ROOT).as_posix() in SQL_EXTRA_FILES


# 仓储之外的 SQL 来源：软删除片段、持久层测试里的手写 SQL。
SQL_EXTRA_FILES = {
    "src/OpenAICanvas.Persistence/SoftDelete.cs",
    "tests/OpenAICanvas.Tests/Persistence/RepositoryTests.cs",
    "tests/OpenAICanvas.Tests/Persistence/SchemaMigratorTests.cs",
    # 下面这些是 v16–v34 移植期间新增、直接对库发裸 SQL 的测试，不在仓储目录下，
    # 漏掉就会出现"改完名查不到表"的一整类失败（CloudAgentResourceLeaseTests 等）。
    "tests/OpenAICanvas.Tests/Application/CanvasHistoryTests.cs",
    "tests/OpenAICanvas.Tests/Application/VideoFormulaBillingTests.cs",
    "tests/OpenAICanvas.Tests/CloudAgent/CloudAgentJournalTests.cs",
    "tests/OpenAICanvas.Tests/Persistence/CloudAgentResourceLeaseTests.cs",
}


def load_dump() -> list[dict]:
    with DUMP.open(encoding="utf-8") as handle:
        return json.load(handle)


def build_map(tables: list[dict]):
    table_map: dict[str, str] = {}
    column_plan: list[tuple[str, str, str]] = []
    collisions: list[str] = []
    for table in tables:
        old_table = table["table"]
        table_map[old_table] = physical_table(old_table)
        if old_table == LEDGER_TABLE:
            continue
        seen: dict[str, str] = {}
        for column in table["columns"]:
            if not column.get("isColumn", True):
                continue
            old = column["name"]
            if old in LEDGER_COLUMNS:
                continue
            new = physical_column(old_table, old)
            if new in seen:
                collisions.append(f"column collision {old_table}: {seen[new]} / {old} -> {new}")
            seen[new] = old
            if new != old:
                column_plan.append((old_table, old, new))
    table_counts = collections.Counter(table_map.values())
    for new, count in table_counts.items():
        if count > 1:
            collisions.append(f"table collision {new} x{count}")
    return table_map, column_plan, collisions


def word_pattern(name: str) -> re.Pattern[str]:
    return re.compile(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])")


def scan_sources(pattern: re.Pattern[str], skip: Path | None = None):
    per_file: collections.Counter[str] = collections.Counter()
    total = 0
    for path in ROOT.rglob("*.cs"):
        if "obj" in path.parts or "bin" in path.parts:
            continue
        if skip is not None and path == skip:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        hits = len(pattern.findall(text))
        if hits:
            per_file[str(path.relative_to(ROOT))] = hits
            total += hits
    return per_file, total


def write_plan_cs(tables: list[dict], table_map: dict[str, str], column_plan, path: Path) -> None:
    lines = [
        "// <auto-generated />",
        "// 由 scripts/rename-schema-identifiers.py --plan-cs 生成，请勿手工编辑。",
        "// 本文件是 v35 迁移的冻结快照：v35 一旦发布，改名计划就不得再变动，",
        "// 否则已迁移的库与新库会收敛到不同结构。后续结构变更请追加新的迁移版本。",
        "#nullable enable",
        "using System.Collections.Generic;",
        "",
        "namespace OpenAICanvas.Persistence.Schema;",
        "",
        "/// <summary>v35 迁移用的改名计划：物理名从 snake_case 改为 camelCase。</summary>",
        "public static class CamelCaseRenamePlan",
        "{",
        "    /// <summary>列改名（表名保持旧名，列改名先于表改名执行）。</summary>",
        "    public static IReadOnlyList<(string Table, string OldName, string NewName)> Columns { get; } =",
        "    [",
    ]
    for table, old, new in column_plan:
        lines.append(f'        ("{table}", "{old}", "{new}"),')
    lines += [
        "    ];",
        "",
        "    /// <summary>表改名。</summary>",
        "    public static IReadOnlyList<(string OldName, string NewName)> Tables { get; } =",
        "    [",
    ]
    for old, new in table_map.items():
        if old != new:
            lines.append(f'        ("{old}", "{new}"),')
    lines += [
        "    ];",
        "}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path}")


def write_rename_sql(table_map: dict[str, str], column_plan, path: Path) -> None:
    lines = [
        "-- 由 scripts/rename-schema-identifiers.py --rename-sql 生成。",
        "-- 先把列名去掉下划线，再改表名（列改名时表名还是旧名）。",
    ]
    for table, old, new in column_plan:
        lines.append(f'ALTER TABLE "{table}" RENAME COLUMN "{old}" TO "{new}";')
    for old, new in table_map.items():
        if old != new:
            lines.append(f'ALTER TABLE "{old}" RENAME TO "{new}";')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def _string_spans(text: str):
    """找出 C# 源码里的字符串字面量区间（跳过注释）。

    返回 [(start, end, kind)]，区间不含定界符。kind 决定插入 SQL 双引号时的转义方式：
    raw（``\"\"\"...\"\"\"``）直接插入 ``"``；verbatim（``@"..."``）需要写成 ``""``；
    regular（``"..."`` / ``$"..."``）需要写成 ``\\"``。写错转义会直接把 C# 源码改坏。
    """
    spans = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            j = text.find(chr(10), i)
            i = n if j < 0 else j + 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        prefix_end = None
        if ch == "$" and i + 1 < n and text[i + 1] == "@" and i + 2 < n and text[i + 2] == '"':
            prefix_end = i + 2
        elif ch == "@" and i + 1 < n and text[i + 1] == "$" and i + 2 < n and text[i + 2] == '"':
            prefix_end = i + 2
        elif ch == "@" and i + 1 < n and text[i + 1] == '"':
            prefix_end = i + 1
        elif ch == "$" and i + 1 < n and text[i + 1] == '"':
            prefix_end = i + 1
        elif ch == '"':
            prefix_end = i
        if prefix_end is None:
            i += 1
            continue
        quote_start = prefix_end
        verbatim = text[i] == "@" or (i + 1 < n and text[i] == "$" and text[i + 1] == "@") or (i + 1 < n and text[i] == "@" and text[i + 1] == "$")
        run = 0
        while quote_start + run < n and text[quote_start + run] == '"':
            run += 1
        if run >= 3:
            close = text.find('"' * run, quote_start + run)
            if close < 0:
                break
            spans.append((quote_start + run, close, "raw"))
            i = close + run
            continue
        j = quote_start + 1
        while j < n:
            if text[j] == '"':
                if verbatim and j + 1 < n and text[j + 1] == '"':
                    j += 2
                    continue
                break
            if not verbatim and text[j] == chr(92):
                j += 2
                continue
            j += 1
        spans.append((quote_start + 1, j, "verbatim" if verbatim else "regular"))
        i = j + 1
    return spans


# 各字面量种类下，一个 SQL 双引号在 C# 源码里的写法。
QUOTE_TOKENS = {"raw": '"', "verbatim": '""', "regular": "\\\""}


def _quote_bounds(span: str, start: int, end: int, kind: str) -> bool:
    """标识符是否已经被 SQL 双引号包裹（按字面量种类识别转义写法）。"""
    if kind == "regular":
        return span[max(0, start - 2):start] == '\\"' and span[end:end + 2] == '\\"'
    return start > 0 and span[start - 1] == '"' and end < len(span) and span[end] == '"'


def _single_quoted_regions(sql: str):
    regions = []
    i = 0
    n = len(sql)
    while i < n:
        if sql[i] == chr(39):
            j = i + 1
            while j < n:
                if sql[j] == chr(39):
                    if j + 1 < n and sql[j + 1] == chr(39):
                        j += 2
                        continue
                    break
                j += 1
            regions.append((i, j + 1))
            i = j + 1
            continue
        i += 1
    return regions


def rewrite_sql_span(sql: str, pattern: re.Pattern[str], renames: dict[str, str], kind: str = "raw"):
    return _rewrite_sql_span(sql, pattern, renames, kind)


def review_code(renames: dict[str, str], needle: str):
    pattern = re.compile(r"(?<![A-Za-z0-9_@])(" + "|".join(sorted((re.escape(k) for k in renames), key=len, reverse=True)) + r")(?![A-Za-z0-9_])")
    for path in sorted(ROOT.rglob("*.cs")):
        if "obj" in path.parts or "bin" in path.parts:
            continue
        relative = str(path.relative_to(ROOT))
        if needle and needle not in relative:
            continue
        if not is_sql_source(path):
            continue
        text = path.read_text(encoding="utf-8")
        for start, end, _kind in _string_spans(text):
            sql = text[start:end]
            regions = _single_quoted_regions(sql)
            for match in pattern.finditer(sql):
                if any(a <= match.start() < b for a, b in regions):
                    continue
                if match.start() > 0 and sql[match.start() - 1] == "@":
                    continue
                context = sql[max(0, match.start() - 36): match.end() + 36].replace(chr(10), " ")
                print(f"{relative}: {context}")


SQL_KEYWORDS = (
    "select", "from", "where", "join", "insert", "update", "delete", "values",
    "set", "group", "order", "having", "union", "limit", "offset", "on", "as",
    "into", "conflict", "returning", "exists", "count", "sum", "coalesce",
)


def report_bare(renames: dict[str, str]) -> None:
    """列出改写器会给"裸标识符"补引号的落点，供人工审核。

    补引号只对真正的 SQL 片段成立；如果某个字面量其实是 C# 侧拼名字用的片段
    （例如 "user_daily_activities." + Quote(column)），补引号会破坏代码——
    这类落点必须在审核里逐条确认。
    """
    pattern = re.compile(r"(?<![A-Za-z0-9_@])(" + "|".join(sorted((re.escape(k) for k in renames), key=len, reverse=True)) + r")(?![A-Za-z0-9_])")
    buckets: dict[str, list[str]] = {"sql_like": [], "other": []}
    for path in sorted(ROOT.rglob("*.cs")):
        if "obj" in path.parts or "bin" in path.parts or not is_sql_source(path):
            continue
        relative = str(path.relative_to(ROOT))
        text = path.read_text(encoding="utf-8")
        for start, end, literal_kind in _string_spans(text):
            span = text[start:end]
            regions = _single_quoted_regions(span)
            for match in pattern.finditer(span):
                if any(a <= match.start() < b for a, b in regions):
                    continue
                if match.start() > 0 and span[match.start() - 1] == "@":
                    continue
                whole_span = not span[:match.start()].strip() and not span[match.end():].strip()
                if whole_span or _quote_bounds(span, match.start(), match.end(), literal_kind):
                    continue
                line = text.count(chr(10), 0, start + match.start()) + 1
                lowered = span.lower()
                kind = "sql_like" if any(k in lowered for k in SQL_KEYWORDS) else "other"
                context = span[max(0, match.start() - 30): match.end() + 30].replace(chr(10), " ")
                buckets[kind].append(f"{relative}:{line}: {match.group(0)} -> {renames[match.group(0)]} | {context}")

    for kind in ("sql_like", "other"):
        print(f"== {kind}: {len(buckets[kind])}")
        for item in buckets[kind]:
            print("  " + item)


def _rewrite_sql_span(sql: str, pattern: re.Pattern[str], renames: dict[str, str], kind: str = "raw"):
    # 整个字面量是迁移契约值（迁移名/校验和）时原样保留。
    if sql.strip() in _protected_literals():
        return sql, 0
    regions = _single_quoted_regions(sql)
    token = QUOTE_TOKENS[kind]
    out = []
    last = 0
    count = 0
    for match in pattern.finditer(sql):
        start, end = match.span()
        if any(a <= start < b for a, b in regions):
            continue
        if start > 0 and sql[start - 1] == "@":
            continue
        # 整个字面量就是一个标识符（表名/列名常量、参数值、集合元素）：
        # 它是被当作"名字"使用的，只能原地替换，需要引号的调用点由
        # Dialect.Quote / RepositoryBase.Quote 负责。
        whole_span = not sql[:start].strip() and not sql[end:].strip()
        old = match.group(0)
        new = renames[old]
        out.append(sql[last:start])
        if whole_span or _quote_bounds(sql, start, end, kind):
            out.append(new)
        else:
            out.append(token + new + token)
        last = end
        count += 1
    out.append(sql[last:])
    return "".join(out), count


# Quote("标识符") 的参数：已经由 SqlBuilder.Quote 在 SQL 层加了双引号，只需改名、不能再补引号。
QUOTE_ARG_PATTERN = re.compile(r'(Quote\(\s*)"([^"\\\n]*)"')


def rewrite_quote_args(text: str, renames: dict[str, str]) -> tuple[str, int]:
    """改写 ``Quote("标识符")`` 里的标识符。

    为什么单独走一遍：这类参数常常长在**插值字符串的表达式里**
    （``$"DELETE FROM {Quote("cloud_agent_resource_leases")} WHERE ..."``），
    而 :func:`_string_spans` 是按引号配对切片的——它会在这里被内层引号提前截断，
    把标识符甩到"代码区"，于是被静默漏掉（v16–v34 移植新增的 4 个仓储正好全是这种写法）。
    单独按源码文本处理即可，且不能补引号（`Quote` 已经引了）。
    """
    hits = 0

    def replace(match: "re.Match[str]") -> str:
        nonlocal hits
        name = match.group(2)
        renamed = renames.get(name)
        if renamed is None or renamed == name:
            return match.group(0)
        hits += 1
        return match.group(1) + '"' + renamed + '"'

    return QUOTE_ARG_PATTERN.sub(replace, text), hits


def rewrite_code(renames: dict[str, str], apply: bool):
    pattern = re.compile(r"(?<![A-Za-z0-9_@])(" + "|".join(sorted((re.escape(k) for k in renames), key=len, reverse=True)) + r")(?![A-Za-z0-9_])")
    total_files = 0
    total_hits = 0
    for path in sorted(ROOT.rglob("*.cs")):
        if "obj" in path.parts or "bin" in path.parts:
            continue
        if not is_sql_source(path):
            continue
        text = path.read_text(encoding="utf-8")
        text, hits = rewrite_quote_args(text, renames)
        spans = _string_spans(text)
        pieces = []
        last = 0
        for start, end, literal_kind in spans:
            new_sql, n = rewrite_sql_span(text[start:end], pattern, renames, literal_kind)
            if n:
                pieces.append(text[last:start])
                pieces.append(new_sql)
                last = end
                hits += n
        if hits:
            pieces.append(text[last:])
            total_files += 1
            total_hits += hits
            print(f"  {hits:4d}  {path.relative_to(ROOT)}")
            if apply:
                path.write_text("".join(pieces), encoding="utf-8")
    print(f"files={total_files} replaced={total_hits} applied={apply}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", action="store_true")
    parser.add_argument("--plan-cs", metavar="PATH")
    parser.add_argument("--rename-sql", metavar="PATH")
    parser.add_argument("--rewrite-code", action="store_true")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--review", metavar="PATH_SUBSTRING")
    parser.add_argument("--report-bare", action="store_true")
    options = parser.parse_args()

    tables = load_dump()
    table_map, column_plan, collisions = build_map(tables)
    renames = {old: new for _, old, new in column_plan}
    for old, new in table_map.items():
        if old != new:
            renames.setdefault(old, new)

    if options.rewrite_code:
        rewrite_code(renames, options.apply)
        return 0

    if options.review is not None:
        review_code(renames, options.review)
        return 0

    if options.report_bare:
        report_bare(renames)
        return 0

    if options.plan_cs:
        write_plan_cs(tables, table_map, column_plan, Path(options.plan_cs))
        return 0

    if options.rename_sql:
        write_rename_sql(table_map, column_plan, Path(options.rename_sql))
        return 0

    if not options.report:
        parser.print_help()
        return 1

    all_columns = sorted({c["name"] for t in tables for c in t["columns"] if c.get("isColumn", True)})
    column_regex = re.compile(r"(?<![A-Za-z0-9_])(" + "|".join(re.escape(n) for n in all_columns) + r")(?![A-Za-z0-9_])")
    table_regex = re.compile(r"(?<![A-Za-z0-9_])(" + "|".join(re.escape(n) for n in table_map) + r")(?![A-Za-z0-9_])")

    column_files, column_total = scan_sources(column_regex)
    table_files, table_total = scan_sources(table_regex)

    print(f"tables={len(table_map)} renamed_tables={sum(1 for a, b in table_map.items() if a != b)}")
    print(f"columns={len(all_columns)} renamed_columns={len(column_plan)}")
    print(f"collisions={collisions if collisions else 'none'}")
    print(f"code_column_refs={column_total} files={len(column_files)}")
    print(f"code_table_refs={table_total} files={len(table_files)}")
    print("top column files:")
    for path, count in column_files.most_common(10):
        print(f"  {count:5d}  {path}")
    print("top table files:")
    for path, count in table_files.most_common(10):
        print(f"  {count:5d}  {path}")
    print("sample renames:")
    for table, old, new in column_plan[:6]:
        print(f"  {table}: {old} -> {new}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
