// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>CloudAgentCanvasMutation</c>，数据库表 <c>cloud_agent_canvas_mutations</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentCanvasMutation
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>run_id</c>（maxLength=80）</summary>
    [JsonPropertyName("runId")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>step_id</c>（maxLength=160）</summary>
    [JsonPropertyName("stepId")]
    public string StepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>before_snapshot_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("beforeSnapshotHash")]
    public string BeforeSnapshotHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>after_snapshot_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("afterSnapshotHash")]
    public string AfterSnapshotHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>before_json</c></summary>
    [JsonIgnore]
    public string BeforeJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>has_submitted_task</c></summary>
    [JsonPropertyName("hasSubmittedTask")]
    public bool HasSubmittedTask { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>undone_at</c></summary>
    [JsonPropertyName("undoneAt")]
    [GoOmitEmpty]
    public DateTime? UndoneAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CloudAgentExecution</c>，数据库表 <c>cloud_agent_executions</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentExecution
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>active_task_id</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string ActiveTaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>media_task_id</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string MediaTaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cleanup_pending</c>（not null）</summary>
    [JsonPropertyName("")]
    public bool CleanupPending { get; set; }

    /// <summary>数据库列 <c>failure_message</c>（maxLength=1000）</summary>
    [JsonPropertyName("")]
    public string FailureMessage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>state_json</c></summary>
    [JsonPropertyName("")]
    public string StateJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("")]
    public DateTime UpdatedAt { get; set; }
}
