// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>CloudAgentCanvasMutation</c>，数据库表 <c>cloudAgentCanvasMutations</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentCanvasMutation
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>runId</c>（maxLength=80）</summary>
    [JsonPropertyName("runId")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvasId</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stepId</c>（maxLength=160）</summary>
    [JsonPropertyName("stepId")]
    public string StepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>beforeSnapshotHash</c>（maxLength=64）</summary>
    [JsonPropertyName("beforeSnapshotHash")]
    public string BeforeSnapshotHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>afterSnapshotHash</c>（maxLength=64）</summary>
    [JsonPropertyName("afterSnapshotHash")]
    public string AfterSnapshotHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>beforeJson</c></summary>
    [JsonIgnore]
    public string BeforeJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>hasSubmittedTask</c></summary>
    [JsonPropertyName("hasSubmittedTask")]
    public bool HasSubmittedTask { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>undoneAt</c></summary>
    [JsonPropertyName("undoneAt")]
    [GoOmitEmpty]
    public DateTime? UndoneAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CloudAgentEventRecord</c>，数据库表 <c>cloudAgentEventRecords</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentEventRecord
{
    /// <summary>数据库列 <c>runId</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sequence</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("")]
    public long Sequence { get; set; }

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>eventJson</c>（not null）</summary>
    [JsonPropertyName("")]
    public string EventJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CloudAgentExecution</c>，数据库表 <c>cloudAgentExecutions</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentExecution
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>checkpointVersion</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("")]
    public long CheckpointVersion { get; set; }

    /// <summary>数据库列 <c>conversationId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string ConversationID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>parentId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string ParentID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>eventCount</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long EventCount { get; set; }

    /// <summary>数据库列 <c>messageCount</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long MessageCount { get; set; }

    /// <summary>数据库列 <c>canvasId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>activeTaskId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string ActiveTaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mediaTaskId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string MediaTaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cleanupPending</c>（not null）</summary>
    [JsonPropertyName("")]
    public bool CleanupPending { get; set; }

    /// <summary>数据库列 <c>failureMessage</c>（maxLength=1000）</summary>
    [JsonPropertyName("")]
    public string FailureMessage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stateJson</c></summary>
    [JsonPropertyName("")]
    public string StateJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonIgnore]
    public List<CloudAgentEventRecord> Journal { get; set; } = null!;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonIgnore]
    public List<CloudAgentMessageRecord> Transcript { get; set; } = null!;
}

/// <summary>
/// 对应 Go <c>CloudAgentMessageRecord</c>，数据库表 <c>cloudAgentMessageRecords</c>。
/// 源文件：internal/model/cloud_agent.go
/// </summary>
public class CloudAgentMessageRecord
{
    /// <summary>数据库列 <c>runId</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24，主键）</summary>
    [JsonPropertyName("")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sequence</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("")]
    public long Sequence { get; set; }

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>messageJson</c>（not null）</summary>
    [JsonPropertyName("")]
    public string MessageJSON { get; set; } = string.Empty;
}
