// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>CloudAgentResourceLease</c>，数据库表 <c>cloudAgentResourceLeases</c>。
/// 源文件：internal/model/cloud_agent_resource_lease.go
/// </summary>
public class CloudAgentResourceLease
{
    /// <summary>数据库列 <c>userId</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>runId</c>（maxLength=80）</summary>
    [JsonPropertyName("")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ownerId</c>（maxLength=160，主键）</summary>
    [JsonPropertyName("")]
    public string OwnerID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resourceId</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("")]
    public DateTime ExpiresAt { get; set; }
}
