// <auto-generated />
// 由 scripts/generate-entities.py 生成，请勿手工编辑。
// 对应 Go: internal/model/*.go 的 `type X string` 与 const 块。
namespace OpenAICanvas.Domain.Entities;

/// <summary>对应 Go <c>AnnouncementLevel</c>。JSON 中即为字符串字面量。</summary>
public static class AnnouncementLevel
{
    public const string AnnouncementLevelInfo = "info";
    public const string AnnouncementLevelSuccess = "success";
    public const string AnnouncementLevelWarning = "warning";
    public const string AnnouncementLevelCritical = "critical";
}

/// <summary>对应 Go <c>AnnouncementStatus</c>。JSON 中即为字符串字面量。</summary>
public static class AnnouncementStatus
{
    public const string AnnouncementStatusActive = "active";
    public const string AnnouncementStatusClosed = "closed";
}

/// <summary>对应 Go <c>ApiCallStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ApiCallStatus
{
    public const string ApiCallStatusSucceeded = "succeeded";
    public const string ApiCallStatusFailed = "failed";
}

/// <summary>对应 Go <c>AssetCategory</c>。JSON 中即为字符串字面量。</summary>
public static class AssetCategory
{
    public const string AssetCategoryCharacter = "character";
    public const string AssetCategoryEnvironment = "environment";
    public const string AssetCategoryProp = "prop";
    public const string AssetCategoryMaterial = "material";
    public const string AssetCategoryOther = "other";
}

/// <summary>对应 Go <c>AssetVersionStatus</c>。JSON 中即为字符串字面量。</summary>
public static class AssetVersionStatus
{
    public const string AssetVersionStatusDraft = "draft";
    public const string AssetVersionStatusReview = "review";
    public const string AssetVersionStatusConfirmed = "confirmed";
    public const string AssetVersionStatusArchived = "archived";
}

/// <summary>对应 Go <c>BillingStatus</c>。JSON 中即为字符串字面量。</summary>
public static class BillingStatus
{
    public const string BillingStatusReserved = "reserved";
    public const string BillingStatusRunning = "running";
    public const string BillingStatusSettled = "settled";
    public const string BillingStatusRefunded = "refunded";
    public const string BillingStatusUncertain = "uncertain";
}

/// <summary>对应 Go <c>ChannelInterfaceType</c>。JSON 中即为字符串字面量。</summary>
public static class ChannelInterfaceType
{
    public const string ChannelInterfaceChatCompletion = "chat-completion";
    public const string ChannelInterfaceOpenAIResponse = "openai-response";
    public const string ChannelInterfaceClaudeAPI = "claude-api";
    public const string ChannelInterfaceOpenAIImage = "openai-image";
    public const string ChannelInterfaceGrokImage = "grok-image";
    public const string ChannelInterfaceVolcengineArkImage = "volcengine-ark-image";
    public const string ChannelInterfaceVolcengineJiMengImage = "volcengine-jimeng-image";
    public const string ChannelInterfaceGeminiImage = "gemini-image";
    public const string ChannelInterfaceOpenAIAudio = "openai-audio";
    public const string ChannelInterfaceAsyncAudio = "async-audio";
    public const string ChannelInterfaceNewAPIVideo = "newapi";
    public const string ChannelInterfaceNewAPIChannel1 = "newapi-channel-1";
    public const string ChannelInterfaceNewAPIChannel2 = "newapi-channel-2";
    public const string ChannelInterfaceXAIVideo = "xai-video";
    public const string ChannelInterfaceVolcengineArkVideo = "volcengine-ark-video";
    public const string ChannelInterfaceVolcengineJiMengVideo = "volcengine-jimeng-video";
    public const string ChannelInterfaceGeminiVeo = "gemini-veo";
    public const string ChannelInterfaceNovitaVideo = "novita-video";
    public const string ChannelInterfaceMiniMaxVideo = "minimax-video";
    public const string ChannelInterfaceAgnesVideo = "agnes-video";
    public const string ChannelInterfaceRunningHubImage = "runninghub-workflow-image";
    public const string ChannelInterfaceRunningHubVideo = "runninghub-workflow-video";
    public const string ChannelInterfaceRunningHubAudio = "runninghub-workflow-audio";
}

/// <summary>对应 Go <c>ChannelScope</c>。JSON 中即为字符串字面量。</summary>
public static class ChannelScope
{
    public const string ChannelScopeSystem = "system";
    public const string ChannelScopeUser = "user";
}

/// <summary>对应 Go <c>CreditLedgerType</c>。JSON 中即为字符串字面量。</summary>
public static class CreditLedgerType
{
    public const string CreditLedgerRedeem = "redeem";
    public const string CreditLedgerAdminGrant = "admin_grant";
    public const string CreditLedgerReserve = "reserve";
    public const string CreditLedgerConsume = "consume";
    public const string CreditLedgerRefund = "refund";
    public const string CreditLedgerAdminAdjust = "admin_adjustment";
    public const string CreditLedgerSignupBonus = "signup_bonus";
    public const string CreditLedgerCheckinBonus = "checkin_bonus";
    public const string CreditLedgerPaymentTopup = "payment_topup";
}

/// <summary>对应 Go <c>PaymentNotificationStatus</c>。JSON 中即为字符串字面量。</summary>
public static class PaymentNotificationStatus
{
    public const string PaymentNotificationPending = "pending";
    public const string PaymentNotificationProcessed = "processed";
    public const string PaymentNotificationFailed = "failed";
}

/// <summary>对应 Go <c>PaymentOrderStatus</c>。JSON 中即为字符串字面量。</summary>
public static class PaymentOrderStatus
{
    public const string PaymentOrderCreated = "created";
    public const string PaymentOrderPending = "pending";
    public const string PaymentOrderClosing = "closing";
    public const string PaymentOrderClosed = "closed";
    public const string PaymentOrderCredited = "credited";
    public const string PaymentOrderCreateFailed = "create_failed";
}

/// <summary>对应 Go <c>PaymentReconciliationResult</c>。JSON 中即为字符串字面量。</summary>
public static class PaymentReconciliationResult
{
    public const string PaymentReconciliationMatched = "matched";
    public const string PaymentReconciliationRecovered = "recovered";
    public const string PaymentReconciliationLocalOrderNotFound = "local_order_not_found";
    public const string PaymentReconciliationProviderRecordMissing = "provider_record_missing";
    public const string PaymentReconciliationAmountMismatch = "amount_mismatch";
    public const string PaymentReconciliationTradeNoMismatch = "trade_no_mismatch";
    public const string PaymentReconciliationCreditFailed = "credit_failed";
}

/// <summary>对应 Go <c>PaymentReconciliationStatus</c>。JSON 中即为字符串字面量。</summary>
public static class PaymentReconciliationStatus
{
    public const string PaymentReconciliationRunning = "running";
    public const string PaymentReconciliationCompleted = "completed";
    public const string PaymentReconciliationFailed = "failed";
}

/// <summary>对应 Go <c>ProjectStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ProjectStatus
{
    public const string ProjectStatusActive = "active";
    public const string ProjectStatusArchived = "archived";
}

/// <summary>对应 Go <c>ProjectUnitKind</c>。JSON 中即为字符串字面量。</summary>
public static class ProjectUnitKind
{
    public const string ProjectUnitKindChapter = "chapter";
    public const string ProjectUnitKindEpisode = "episode";
}

/// <summary>对应 Go <c>ProjectUnitStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ProjectUnitStatus
{
    public const string ProjectUnitStatusDraft = "draft";
    public const string ProjectUnitStatusReady = "ready";
    public const string ProjectUnitStatusCompleted = "completed";
}

/// <summary>对应 Go <c>ProviderCancelStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ProviderCancelStatus
{
    public const string ProviderCancelStatusRequested = "requested";
    public const string ProviderCancelStatusConfirmed = "confirmed";
    public const string ProviderCancelStatusUncertain = "uncertain";
}

/// <summary>对应 Go <c>RedeemCodeStatus</c>。JSON 中即为字符串字面量。</summary>
public static class RedeemCodeStatus
{
    public const string RedeemCodeUnused = "unused";
    public const string RedeemCodeRedeemed = "redeemed";
    public const string RedeemCodeDisabled = "disabled";
}

/// <summary>对应 Go <c>ResourceDeletionStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ResourceDeletionStatus
{
    public const string ResourceDeletionStatusPending = "pending";
    public const string ResourceDeletionStatusProcessing = "processing";
}

/// <summary>对应 Go <c>ResourceStatus</c>。JSON 中即为字符串字面量。</summary>
public static class ResourceStatus
{
    public const string ResourceStatusPending = "pending";
    public const string ResourceStatusReady = "ready";
    public const string ResourceStatusFailed = "failed";
    public const string ResourceStatusDeleted = "deleted";
}

/// <summary>对应 Go <c>TaskStatus</c>。JSON 中即为字符串字面量。</summary>
public static class TaskStatus
{
    public const string TaskStatusQueued = "queued";
    public const string TaskStatusRunning = "running";
    public const string TaskStatusSucceeded = "succeeded";
    public const string TaskStatusFailed = "failed";
    public const string TaskStatusCancelled = "cancelled";
    public const string TaskStatusTextReplay = "text_replay";
}

/// <summary>对应 Go <c>UserRole</c>。JSON 中即为字符串字面量。</summary>
public static class UserRole
{
    public const string UserRoleAdmin = "admin";
    public const string UserRoleUser = "user";
}

/// <summary>对应 Go <c>UserStatus</c>。JSON 中即为字符串字面量。</summary>
public static class UserStatus
{
    public const string UserStatusActive = "active";
    public const string UserStatusDisabled = "disabled";
}

/// <summary>对应 Go <c>WorkflowStatus</c>。JSON 中即为字符串字面量。</summary>
public static class WorkflowStatus
{
    public const string WorkflowStatusActive = "active";
    public const string WorkflowStatusCompleted = "completed";
    public const string WorkflowStatusFailed = "failed";
}

/// <summary>对应 Go <c>WorkflowStepStatus</c>。JSON 中即为字符串字面量。</summary>
public static class WorkflowStepStatus
{
    public const string WorkflowStepStatusPending = "pending";
    public const string WorkflowStepStatusReady = "ready";
    public const string WorkflowStepStatusRunning = "running";
    public const string WorkflowStepStatusReview = "review";
    public const string WorkflowStepStatusCompleted = "completed";
    public const string WorkflowStepStatusFailed = "failed";
    public const string WorkflowStepStatusSkipped = "skipped";
}
