// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>ArkPrivateAssetBinding</c>，数据库表 <c>arkPrivateAssetBindings</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class ArkPrivateAssetBinding
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectName</c>（maxLength=160）</summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetGroupId</c>（maxLength=120）</summary>
    [JsonPropertyName("assetGroupId")]
    public string AssetGroupID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>arkAssetId</c>（maxLength=120）</summary>
    [JsonPropertyName("arkAssetId")]
    public string ArkAssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>SkillFile</c>，数据库表 <c>skillFiles</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class SkillFile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>skillVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("skillVersionId")]
    public string SkillVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>path</c>（maxLength=1000）</summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mimeType</c>（maxLength=255）</summary>
    [JsonPropertyName("mimeType")]
    public string MimeType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>size</c>（maxLength=64）</summary>
    [JsonPropertyName("size")]
    public long Size { get; set; }

    /// <summary>数据库列 <c>sha256</c>（maxLength=64）</summary>
    [JsonPropertyName("sha256")]
    public string SHA256 { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>SkillVersion</c>，数据库表 <c>skillVersions</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class SkillVersion
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>skillId</c>（maxLength=36）</summary>
    [JsonPropertyName("skillId")]
    public string SkillID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>versionLabel</c>（maxLength=64）</summary>
    [JsonPropertyName("versionLabel")]
    public string VersionLabel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>contentHash</c>（maxLength=64）</summary>
    [JsonPropertyName("contentHash")]
    public string ContentHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>entryPath</c>（maxLength=1000）</summary>
    [JsonPropertyName("entryPath")]
    public string EntryPath { get; set; } = string.Empty;

    /// <summary>数据库列 <c>packageKey</c>（maxLength=1000）</summary>
    [JsonPropertyName("packageKey")]
    public string PackageKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>fileCount</c>（maxLength=64）</summary>
    [JsonPropertyName("fileCount")]
    public long FileCount { get; set; }

    /// <summary>数据库列 <c>totalBytes</c>（maxLength=64）</summary>
    [JsonPropertyName("totalBytes")]
    public long TotalBytes { get; set; }

    /// <summary>数据库列 <c>sourceCommit</c>（maxLength=64）</summary>
    [JsonPropertyName("sourceCommit")]
    public string SourceCommit { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Skill</c>，数据库表 <c>skills</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class Skill
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ownerId</c>（maxLength=36）</summary>
    [JsonPropertyName("ownerId")]
    public string OwnerID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>authorName</c>（maxLength=120）</summary>
    [JsonPropertyName("authorName")]
    public string AuthorName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>authorAvatarUrl</c>（maxLength=1000）</summary>
    [JsonPropertyName("authorAvatarUrl")]
    public string AuthorAvatarURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=80）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>instruction</c></summary>
    [JsonPropertyName("instruction")]
    public string Instruction { get; set; } = string.Empty;

    /// <summary>数据库列 <c>currentVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("currentVersionId")]
    public string CurrentVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>versionLabel</c>（maxLength=64）</summary>
    [JsonPropertyName("versionLabel")]
    public string VersionLabel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>contentHash</c>（maxLength=64）</summary>
    [JsonPropertyName("contentHash")]
    public string ContentHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>fileCount</c>（maxLength=64）</summary>
    [JsonPropertyName("fileCount")]
    public long FileCount { get; set; }

    /// <summary>数据库列 <c>totalBytes</c>（maxLength=64）</summary>
    [JsonPropertyName("totalBytes")]
    public long TotalBytes { get; set; }

    /// <summary>数据库列 <c>sourceType</c>（maxLength=24）</summary>
    [JsonPropertyName("sourceType")]
    public string SourceType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceUrl</c>（maxLength=1000）</summary>
    [JsonPropertyName("sourceUrl")]
    public string SourceURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceRef</c>（maxLength=255）</summary>
    [JsonPropertyName("sourceRef")]
    public string SourceRef { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceSubdir</c>（maxLength=1000）</summary>
    [JsonPropertyName("sourceSubdir")]
    public string SourceSubdir { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceCommit</c>（maxLength=64）</summary>
    [JsonPropertyName("sourceCommit")]
    public string SourceCommit { get; set; } = string.Empty;

    /// <summary>数据库列 <c>syncStatus</c>（maxLength=24）</summary>
    [JsonPropertyName("syncStatus")]
    public string SyncStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>syncError</c></summary>
    [JsonPropertyName("syncError")]
    public string SyncError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>autoUpdate</c></summary>
    [JsonPropertyName("autoUpdate")]
    public bool AutoUpdate { get; set; }

    /// <summary>数据库列 <c>lastCheckedAt</c></summary>
    [JsonPropertyName("lastCheckedAt")]
    public DateTime? LastCheckedAt { get; set; }

    /// <summary>数据库列 <c>lastSyncedAt</c></summary>
    [JsonPropertyName("lastSyncedAt")]
    public DateTime? LastSyncedAt { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=64）</summary>
    [JsonPropertyName("status")]
    public long Status { get; set; }

    /// <summary>数据库列 <c>source</c>（maxLength=64）</summary>
    [JsonPropertyName("source")]
    public long Source { get; set; }

    /// <summary>数据库列 <c>tag</c>（maxLength=32）</summary>
    [JsonPropertyName("tag")]
    public string Tag { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sortWeight</c>（maxLength=64）</summary>
    [JsonPropertyName("sortWeight")]
    public long SortWeight { get; set; }

    /// <summary>数据库列 <c>isPrivate</c></summary>
    [JsonPropertyName("isPrivate")]
    public bool IsPrivate { get; set; }

    /// <summary>数据库列 <c>markdownUrl</c>（maxLength=500）</summary>
    [JsonPropertyName("markdownUrl")]
    public string MarkdownURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>showcaseMediaJson</c></summary>
    [JsonIgnore]
    public string ShowcaseMediaJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>extraInfo</c></summary>
    [JsonPropertyName("extraInfo")]
    public string ExtraInfo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>initialLikeCount</c>（maxLength=64）</summary>
    [JsonPropertyName("initialLikeCount")]
    public long InitialLikeCount { get; set; }

    /// <summary>数据库列 <c>initialAddedCount</c>（maxLength=64）</summary>
    [JsonPropertyName("initialAddedCount")]
    public long InitialAddedCount { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>StorageLocation</c>，数据库表 <c>storageLocations</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class StorageLocation
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scope</c>（maxLength=16）</summary>
    [JsonPropertyName("scope")]
    public string Scope { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ownerId</c>（maxLength=36）</summary>
    [JsonPropertyName("ownerId")]
    public string OwnerID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=24）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>locationDigest</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string LocationDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>valueJson</c></summary>
    [JsonIgnore]
    public string ValueJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>testedDigest</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string TestedDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>testedAt</c></summary>
    [JsonPropertyName("testedAt")]
    [GoOmitEmpty]
    public DateTime? TestedAt { get; set; }

    /// <summary>数据库列 <c>active</c></summary>
    [JsonPropertyName("active")]
    public bool Active { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>SystemSetting</c>，数据库表 <c>systemSettings</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class SystemSetting
{
    /// <summary>数据库列 <c>key</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("key")]
    public string Key { get; set; } = string.Empty;

    /// <summary>数据库列 <c>valueJson</c></summary>
    [JsonPropertyName("valueJson")]
    public string ValueJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>updatedBy</c>（maxLength=36）</summary>
    [JsonPropertyName("updatedBy")]
    public string UpdatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ToolFavorite</c>，数据库表 <c>toolFavorites</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class ToolFavorite
{
    /// <summary>数据库列 <c>id</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("id")]
    public long ID { get; set; }

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>toolId</c>（maxLength=64）</summary>
    [JsonPropertyName("toolId")]
    public long ToolID { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Tool</c>，数据库表 <c>tools</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class Tool
{
    /// <summary>数据库列 <c>id</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("id")]
    public long ID { get; set; }

    /// <summary>数据库列 <c>type</c>（maxLength=24）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>labelEn</c>（maxLength=120）</summary>
    [JsonPropertyName("labelEn")]
    public string LabelEn { get; set; } = string.Empty;

    /// <summary>数据库列 <c>label</c>（maxLength=120）</summary>
    [JsonPropertyName("label")]
    public string Label { get; set; } = string.Empty;

    /// <summary>数据库列 <c>desc</c>（maxLength=500）</summary>
    [JsonPropertyName("desc")]
    public string Desc { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tag</c>（maxLength=64）</summary>
    [JsonPropertyName("tag")]
    public string Tag { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cover</c>（maxLength=500）</summary>
    [JsonPropertyName("cover")]
    public string Cover { get; set; } = string.Empty;

    /// <summary>数据库列 <c>extraInfoJson</c></summary>
    [JsonIgnore]
    public string ExtraInfoJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>prompt</c></summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ratio</c>（maxLength=32）</summary>
    [JsonPropertyName("ratio")]
    public string Ratio { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mediaUrl</c>（maxLength=500）</summary>
    [JsonPropertyName("mediaUrl")]
    public string MediaURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ownerId</c>（maxLength=36）</summary>
    [JsonPropertyName("ownerId")]
    public string OwnerID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source</c>（maxLength=16）</summary>
    [JsonPropertyName("source")]
    public string Source { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>visibility</c>（maxLength=16）</summary>
    [JsonPropertyName("visibility")]
    public string Visibility { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sortWeight</c>（maxLength=64）</summary>
    [JsonPropertyName("sortWeight")]
    public long SortWeight { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserDailyActivity</c>，数据库表 <c>userDailyActivities</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class UserDailyActivity
{
    /// <summary>数据库列 <c>id</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>day</c></summary>
    [JsonPropertyName("day")]
    public DateTime Day { get; set; }

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>firstActiveAt</c></summary>
    [JsonPropertyName("firstActiveAt")]
    public DateTime? FirstActiveAt { get; set; }

    /// <summary>数据库列 <c>lastActiveAt</c></summary>
    [JsonPropertyName("lastActiveAt")]
    public DateTime? LastActiveAt { get; set; }

    /// <summary>数据库列 <c>loginCount</c>（maxLength=64）</summary>
    [JsonPropertyName("loginCount")]
    public long LoginCount { get; set; }

    /// <summary>数据库列 <c>taskCount</c>（maxLength=64）</summary>
    [JsonPropertyName("taskCount")]
    public long TaskCount { get; set; }

    /// <summary>数据库列 <c>agentMessageCount</c>（maxLength=64）</summary>
    [JsonPropertyName("agentMessageCount")]
    public long AgentMessageCount { get; set; }

    /// <summary>数据库列 <c>canvasActive</c></summary>
    [JsonPropertyName("canvasActive")]
    public bool CanvasActive { get; set; }

    /// <summary>数据库列 <c>assetCount</c>（maxLength=64）</summary>
    [JsonPropertyName("assetCount")]
    public long AssetCount { get; set; }

    /// <summary>数据库列 <c>resourceCount</c>（maxLength=64）</summary>
    [JsonPropertyName("resourceCount")]
    public long ResourceCount { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserDailyUploadUsage</c>，数据库表 <c>userDailyUploadUsages</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class UserDailyUploadUsage
{
    /// <summary>数据库列 <c>id</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>day</c>（maxLength=10）</summary>
    [JsonPropertyName("day")]
    public string Day { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bytes</c>（maxLength=64）</summary>
    [JsonPropertyName("bytes")]
    public long Bytes { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserOSSSetting</c>，数据库表 <c>userOssSettings</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class UserOSSSetting
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>valueJson</c></summary>
    [JsonIgnore]
    public string ValueJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserSkillState</c>，数据库表 <c>userSkillStates</c>。
/// 源文件：internal/model/models_platform.go
/// </summary>
public class UserSkillState
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>skillId</c>（maxLength=36）</summary>
    [JsonPropertyName("skillId")]
    public string SkillID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>installedVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("installedVersionId")]
    public string InstalledVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>autoUpdate</c></summary>
    [JsonPropertyName("autoUpdate")]
    public bool AutoUpdate { get; set; }

    /// <summary>数据库列 <c>added</c></summary>
    [JsonPropertyName("added")]
    public bool Added { get; set; }

    /// <summary>数据库列 <c>liked</c></summary>
    [JsonPropertyName("liked")]
    public bool Liked { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
