// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AgentProfile</c>，数据库表 <c>agent_profiles</c>。
/// 源文件：internal/model/models_agent_profile.go
/// </summary>
public class AgentProfile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scope</c>（maxLength=16）</summary>
    [JsonPropertyName("scope")]
    public string Scope { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    [GoOmitEmpty]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    [GoOmitEmpty]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>hash</c>（maxLength=64）</summary>
    [JsonPropertyName("hash")]
    public string Hash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
