// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>BillingOrder</c>，数据库表 <c>billing_orders</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class BillingOrder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>idempotency_key</c>（maxLength=160）</summary>
    [JsonPropertyName("idempotencyKey")]
    public string IdempotencyKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>price_tier_id</c>（maxLength=36）</summary>
    [JsonPropertyName("priceTierId")]
    [GoOmitEmpty]
    public string PriceTierID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>price_tier_version</c>（maxLength=64）</summary>
    [JsonPropertyName("priceTierVersion")]
    public long PriceTierVersion { get; set; }

    /// <summary>数据库列 <c>price_selector_json</c></summary>
    [JsonIgnore]
    public string PriceSelectorJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scene</c>（maxLength=80）</summary>
    [JsonPropertyName("scene")]
    public string Scene { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billing_mode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>price_version</c>（maxLength=64）</summary>
    [JsonPropertyName("priceVersion")]
    public long PriceVersion { get; set; }

    /// <summary>数据库列 <c>unit_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>multiplier_basis_points</c>（maxLength=64）</summary>
    [JsonPropertyName("multiplierBasisPoints")]
    public long MultiplierBasisPoints { get; set; }

    /// <summary>数据库列 <c>quantity</c>（maxLength=64）</summary>
    [JsonPropertyName("quantity")]
    public long Quantity { get; set; }

    /// <summary>数据库列 <c>amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>reserved_amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedAmountMicrocredits")]
    public long ReservedAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>charge_limit_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("chargeLimitMicrocredits")]
    [GoOmitEmpty]
    public long ChargeLimitMicrocredits { get; set; }

    /// <summary>数据库列 <c>actual_amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("actualAmountMicrocredits")]
    public long ActualAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>refunded_amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("refundedAmountMicrocredits")]
    public long RefundedAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>input_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokenPriceMicrocredits")]
    public long InputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>output_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokenPriceMicrocredits")]
    public long OutputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cached_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokenPriceMicrocredits")]
    public long CachedTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>input_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokens")]
    public long InputTokens { get; set; }

    /// <summary>数据库列 <c>output_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokens")]
    public long OutputTokens { get; set; }

    /// <summary>数据库列 <c>cached_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokens")]
    public long CachedTokens { get; set; }

    /// <summary>数据库列 <c>usage_available</c></summary>
    [JsonPropertyName("usageAvailable")]
    public bool UsageAvailable { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_request_id</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    [GoOmitEmpty]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c>（maxLength=1000）</summary>
    [JsonPropertyName("error")]
    [GoOmitEmpty]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolved_by</c>（maxLength=36）</summary>
    [JsonPropertyName("resolvedBy")]
    [GoOmitEmpty]
    public string ResolvedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolution_note</c>（maxLength=500）</summary>
    [JsonPropertyName("resolutionNote")]
    [GoOmitEmpty]
    public string ResolutionNote { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime? StartedAt { get; set; }

    /// <summary>数据库列 <c>settled_at</c></summary>
    [JsonPropertyName("settledAt")]
    public DateTime? SettledAt { get; set; }

    /// <summary>数据库列 <c>refunded_at</c></summary>
    [JsonPropertyName("refundedAt")]
    public DateTime? RefundedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CreditAccount</c>，数据库表 <c>credit_accounts</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class CreditAccount
{
    /// <summary>数据库列 <c>user_id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>available_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableMicrocredits")]
    public long AvailableMicrocredits { get; set; }

    /// <summary>数据库列 <c>reserved_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedMicrocredits")]
    public long ReservedMicrocredits { get; set; }

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CreditLedgerEntry</c>，数据库表 <c>credit_ledger_entries</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class CreditLedgerEntry
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=32）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>available_delta_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableDeltaMicrocredits")]
    public long AvailableDeltaMicrocredits { get; set; }

    /// <summary>数据库列 <c>reserved_delta_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedDeltaMicrocredits")]
    public long ReservedDeltaMicrocredits { get; set; }

    /// <summary>数据库列 <c>available_after_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableAfterMicrocredits")]
    public long AvailableAfterMicrocredits { get; set; }

    /// <summary>数据库列 <c>reserved_after_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedAfterMicrocredits")]
    public long ReservedAfterMicrocredits { get; set; }

    /// <summary>数据库列 <c>billing_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("billingOrderId")]
    [GoOmitEmpty]
    public string BillingOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payment_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeem_code_id</c>（maxLength=36）</summary>
    [JsonPropertyName("redeemCodeId")]
    [GoOmitEmpty]
    public string RedeemCodeID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>actor_user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("actorUserId")]
    [GoOmitEmpty]
    public string ActorUserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    [GoOmitEmpty]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    [GoOmitEmpty]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scene</c>（maxLength=80）</summary>
    [JsonPropertyName("scene")]
    [GoOmitEmpty]
    public string Scene { get; set; } = string.Empty;

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    [GoOmitEmpty]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>reference_key</c>（maxLength=180）</summary>
    [JsonPropertyName("referenceKey")]
    [GoOmitEmpty]
    public string? ReferenceKey { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ModelPricing</c>，数据库表 <c>model_pricings</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class ModelPricing
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>currency</c>（maxLength=12）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>input_per_million_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("inputPerMillionMicros")]
    public long InputPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>output_per_million_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("outputPerMillionMicros")]
    public long OutputPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>cached_per_million_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedPerMillionMicros")]
    public long CachedPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>per_request_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("perRequestMicros")]
    public long PerRequestMicros { get; set; }

    /// <summary>数据库列 <c>per_media_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("perMediaMicros")]
    public long PerMediaMicros { get; set; }

    /// <summary>数据库列 <c>per_video_second_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("perVideoSecondMicros")]
    public long PerVideoSecondMicros { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>RedeemBatch</c>，数据库表 <c>redeem_batches</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class RedeemBatch
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>count</c>（maxLength=64）</summary>
    [JsonPropertyName("count")]
    public long Count { get; set; }

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codes_cipher</c></summary>
    [JsonIgnore]
    public string CodesCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("availableCount")]
    public long AvailableCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("redeemedCount")]
    public long RedeemedCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("disabledCount")]
    public long DisabledCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("expiredCount")]
    public long ExpiredCount { get; set; }
}

/// <summary>
/// 对应 Go <c>RedeemCode</c>，数据库表 <c>redeem_codes</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class RedeemCode
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>batch_id</c>（maxLength=36）</summary>
    [JsonPropertyName("batchId")]
    public string BatchID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>code_hash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string CodeHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>code_suffix</c>（maxLength=4）</summary>
    [JsonPropertyName("codeSuffix")]
    public string CodeSuffix { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amount_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeemed_by</c>（maxLength=36）</summary>
    [JsonPropertyName("redeemedBy")]
    [GoOmitEmpty]
    public string RedeemedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeemed_at</c></summary>
    [JsonPropertyName("redeemedAt")]
    public DateTime? RedeemedAt { get; set; }

    /// <summary>数据库列 <c>redeemed_ip</c>（maxLength=64）</summary>
    [JsonPropertyName("redeemedIp")]
    [GoOmitEmpty]
    public string RedeemedIP { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
