// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AuthSession</c>，数据库表 <c>authSessions</c>。
/// 源文件：internal/model/models_identity.go
/// </summary>
public class AuthSession
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tokenHash</c></summary>
    [JsonIgnore]
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>EmailVerificationCode</c>，数据库表 <c>emailVerificationCodes</c>。
/// 源文件：internal/model/models_identity.go
/// </summary>
public class EmailVerificationCode
{
    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonIgnore]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>email</c>（maxLength=160）</summary>
    [JsonPropertyName("email")]
    public string Email { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codeHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string CodeHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>purpose</c>（maxLength=32）</summary>
    [JsonPropertyName("purpose")]
    public string Purpose { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>usedAt</c></summary>
    [JsonPropertyName("usedAt")]
    public DateTime? UsedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>OAuthState</c>，数据库表 <c>oAuthStates</c>。
/// 源文件：internal/model/models_identity.go
/// </summary>
public class OAuthState
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=32）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stateHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string StateHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codeVerifier</c>（maxLength=160）</summary>
    [JsonIgnore]
    public string CodeVerifier { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nextPath</c></summary>
    [JsonPropertyName("nextPath")]
    public string NextPath { get; set; } = string.Empty;

    /// <summary>数据库列 <c>acceptedTerms</c>（not null）</summary>
    [JsonPropertyName("acceptedTerms")]
    public bool AcceptedTerms { get; set; }

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>usedAt</c></summary>
    [JsonPropertyName("usedAt")]
    public DateTime? UsedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserIdentity</c>，数据库表 <c>userIdentities</c>。
/// 源文件：internal/model/models_identity.go
/// </summary>
public class UserIdentity
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=32）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>subject</c>（maxLength=160）</summary>
    [JsonPropertyName("subject")]
    public string Subject { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerUsername</c>（maxLength=160）</summary>
    [JsonPropertyName("providerUsername")]
    public string ProviderUsername { get; set; } = string.Empty;

    /// <summary>数据库列 <c>avatarUrl</c></summary>
    [JsonPropertyName("avatarUrl")]
    public string AvatarURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>User</c>，数据库表 <c>users</c>。
/// 源文件：internal/model/models_identity.go
/// </summary>
public class User
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>username</c>（maxLength=80）</summary>
    [JsonPropertyName("username")]
    public string Username { get; set; } = string.Empty;

    /// <summary>数据库列 <c>email</c>（maxLength=160）</summary>
    [JsonPropertyName("email")]
    [GoOmitEmpty]
    public string Email { get; set; } = string.Empty;

    /// <summary>数据库列 <c>phone</c>（maxLength=24）</summary>
    [JsonPropertyName("phone")]
    [GoOmitEmpty]
    public string Phone { get; set; } = string.Empty;

    /// <summary>数据库列 <c>emailVerifiedAt</c></summary>
    [JsonPropertyName("emailVerifiedAt")]
    [GoOmitEmpty]
    public DateTime? EmailVerifiedAt { get; set; }

    /// <summary>数据库列 <c>phoneVerifiedAt</c></summary>
    [JsonPropertyName("phoneVerifiedAt")]
    [GoOmitEmpty]
    public DateTime? PhoneVerifiedAt { get; set; }

    /// <summary>数据库列 <c>displayName</c>（maxLength=80）</summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=24）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>passwordHash</c></summary>
    [JsonIgnore]
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>lastLoginAt</c></summary>
    [JsonPropertyName("lastLoginAt")]
    public DateTime? LastLoginAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
