// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>CreationRun</c>，数据库表 <c>creationRuns</c>。
/// 源文件：internal/model/models_creation.go
/// </summary>
public class CreationRun
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>clientKey</c>（maxLength=120）</summary>
    [JsonIgnore]
    public string ClientKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string CreateHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvasId</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    [GoOmitEmpty]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>executionEpoch</c>（maxLength=64）</summary>
    [JsonPropertyName("executionEpoch")]
    public long ExecutionEpoch { get; set; }

    /// <summary>数据库列 <c>executionOwner</c>（maxLength=120）</summary>
    [JsonPropertyName("executionOwner")]
    public string ExecutionOwner { get; set; } = string.Empty;

    /// <summary>数据库列 <c>leaseExpiresAt</c></summary>
    [JsonPropertyName("leaseExpiresAt")]
    [GoOmitEmpty]
    public DateTime? LeaseExpiresAt { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stateJson</c></summary>
    [JsonIgnore]
    public string StateJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>approvedProposalVersion</c>（maxLength=64）</summary>
    [JsonPropertyName("approvedProposalVersion")]
    [GoOmitEmpty]
    public long ApprovedProposalVersion { get; set; }

    /// <summary>数据库列 <c>approvedProposalHash</c>（maxLength=64）</summary>
    [JsonPropertyName("approvedProposalHash")]
    [GoOmitEmpty]
    public string ApprovedProposalHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>approvedOperationsJson</c></summary>
    [JsonIgnore]
    public string ApprovedOperationsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>approvedCanvasJson</c></summary>
    [JsonIgnore]
    public string ApprovedCanvasJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>approvedAt</c></summary>
    [JsonIgnore]
    public DateTime? ApprovedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CreationSubmission</c>，数据库表 <c>creationSubmissions</c>。
/// 源文件：internal/model/models_creation.go
/// </summary>
public class CreationSubmission
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>runId</c>（maxLength=36）</summary>
    [JsonPropertyName("runId")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>itemKey</c>（maxLength=160）</summary>
    [JsonPropertyName("itemKey")]
    public string ItemKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>proposalVersion</c>（maxLength=64）</summary>
    [JsonIgnore]
    public long ProposalVersion { get; set; }

    /// <summary>数据库列 <c>proposalHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string ProposalHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>requestJson</c></summary>
    [JsonIgnore]
    public string RequestJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>requestHash</c>（maxLength=64）</summary>
    [JsonPropertyName("requestHash")]
    public string RequestHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>quoteJson</c></summary>
    [JsonIgnore]
    public string QuoteJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>priceSignature</c></summary>
    [JsonIgnore]
    public string PriceSignature { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonIgnore]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>approvedAt</c></summary>
    [JsonPropertyName("approvedAt")]
    [GoOmitEmpty]
    public DateTime? ApprovedAt { get; set; }

    /// <summary>数据库列 <c>revokedAt</c></summary>
    [JsonPropertyName("revokedAt")]
    [GoOmitEmpty]
    public DateTime? RevokedAt { get; set; }

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string? TaskID { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonIgnore]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonIgnore]
    public DateTime UpdatedAt { get; set; }
}
