// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>Result</c>，数据库表 <c>results</c>。
/// 源文件：internal/model/models_task.go
/// </summary>
public class Result
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=64）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>url</c></summary>
    [JsonPropertyName("url")]
    public string URL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload</c></summary>
    [JsonPropertyName("payload")]
    public string Payload { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>TaskLog</c>，数据库表 <c>task_logs</c>。
/// 源文件：internal/model/models_task.go
/// </summary>
public class TaskLog
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>trace_id</c>（maxLength=96）</summary>
    [JsonIgnore]
    public string TraceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_id</c>（maxLength=96）</summary>
    [JsonIgnore]
    public string RequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>level</c>（maxLength=24）</summary>
    [JsonPropertyName("level")]
    public string Level { get; set; } = string.Empty;

    /// <summary>数据库列 <c>message</c></summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload</c></summary>
    [JsonPropertyName("payload")]
    public string Payload { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>TaskTextDelta</c>，数据库表 <c>task_text_delta</c>。
/// 源文件：internal/model/models_task.go
/// </summary>
public class TaskTextDelta
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sequence</c>（maxLength=64）</summary>
    [JsonPropertyName("sequence")]
    public long Sequence { get; set; }

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>byte_count</c>（maxLength=64）</summary>
    [JsonPropertyName("byteCount")]
    public long ByteCount { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Task</c>，数据库表 <c>tasks</c>。
/// 源文件：internal/model/models_task.go
/// </summary>
public class Task
{
    /// <summary>数据库列 <c>creation_submission_id</c>（maxLength=36）</summary>
    [JsonPropertyName("creationSubmissionId")]
    [GoOmitEmpty]
    public string? CreationSubmissionID { get; set; }

    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>trace_id</c>（maxLength=96）</summary>
    [JsonIgnore]
    public string TraceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_id</c>（maxLength=96）</summary>
    [JsonIgnore]
    public string RequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=80）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=64）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stage</c>（maxLength=80）</summary>
    [JsonPropertyName("stage")]
    public string Stage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>progress</c>（maxLength=64）</summary>
    [JsonPropertyName("progress")]
    public long Progress { get; set; }

    /// <summary>数据库列 <c>prompt</c></summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=64）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logical_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelId")]
    [GoOmitEmpty]
    public string LogicalModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logical_model_revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelRevisionId")]
    [GoOmitEmpty]
    public string LogicalModelRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>route_id</c>（maxLength=36）</summary>
    [JsonPropertyName("routeId")]
    [GoOmitEmpty]
    public string RouteID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    [GoOmitEmpty]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>route_run</c>（maxLength=64）</summary>
    [JsonIgnore]
    public long RouteRun { get; set; }

    /// <summary>数据库列 <c>billing_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("billingOrderId")]
    [GoOmitEmpty]
    public string BillingOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_request_id</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    [GoOmitEmpty]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_cancel_status</c>（maxLength=24）</summary>
    [JsonPropertyName("providerCancelStatus")]
    [GoOmitEmpty]
    public string ProviderCancelStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_cancel_error</c></summary>
    [JsonPropertyName("providerCancelError")]
    [GoOmitEmpty]
    public string ProviderCancelError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_cancel_attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("providerCancelAttempts")]
    [GoOmitEmpty]
    public long ProviderCancelAttempts { get; set; }

    /// <summary>数据库列 <c>provider_cancel_requested_at</c></summary>
    [JsonPropertyName("providerCancelRequestedAt")]
    [GoOmitEmpty]
    public DateTime? ProviderCancelRequestedAt { get; set; }

    /// <summary>数据库列 <c>provider_cancelled_at</c></summary>
    [JsonPropertyName("providerCancelledAt")]
    [GoOmitEmpty]
    public DateTime? ProviderCancelledAt { get; set; }

    /// <summary>数据库列 <c>provider_cancel_next_check_at</c></summary>
    [JsonPropertyName("providerCancelNextCheckAt")]
    [GoOmitEmpty]
    public DateTime? ProviderCancelNextCheckAt { get; set; }

    /// <summary>数据库列 <c>poll_stage</c>（maxLength=32）</summary>
    [JsonPropertyName("pollStage")]
    [GoOmitEmpty]
    public string PollStage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>next_poll_at</c></summary>
    [JsonPropertyName("nextPollAt")]
    [GoOmitEmpty]
    public DateTime? NextPollAt { get; set; }

    /// <summary>数据库列 <c>lease_owner</c>（maxLength=120）</summary>
    [JsonIgnore]
    public string LeaseOwner { get; set; } = string.Empty;

    /// <summary>数据库列 <c>lease_expires_at</c></summary>
    [JsonIgnore]
    public DateTime? LeaseExpiresAt { get; set; }

    /// <summary>数据库列 <c>input_json</c></summary>
    [JsonPropertyName("inputJson")]
    public string InputJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>result_json</c></summary>
    [JsonPropertyName("resultJson")]
    public string ResultJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>text_draft</c></summary>
    [JsonPropertyName("textDraft")]
    [GoOmitEmpty]
    public string TextDraft { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime? StartedAt { get; set; }

    /// <summary>数据库列 <c>completed_at</c></summary>
    [JsonPropertyName("completedAt")]
    public DateTime? CompletedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
