// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>PaymentNotification</c>，数据库表 <c>payment_notifications</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentNotification
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_id</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_event_id</c>（maxLength=160）</summary>
    [JsonPropertyName("providerEventId")]
    public string ProviderEventID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_config_id</c>（maxLength=36）</summary>
    [JsonPropertyName("providerConfigId")]
    public string ProviderConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchant_order_no</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    [GoOmitEmpty]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payment_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload_digest</c>（maxLength=64）</summary>
    [JsonPropertyName("payloadDigest")]
    public string PayloadDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload_cipher</c></summary>
    [JsonIgnore]
    public string PayloadCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>normalized_json</c></summary>
    [JsonIgnore]
    public string NormalizedJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>last_error</c>（maxLength=1000）</summary>
    [JsonPropertyName("lastError")]
    [GoOmitEmpty]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>next_attempt_at</c></summary>
    [JsonPropertyName("nextAttemptAt")]
    public DateTime NextAttemptAt { get; set; }

    /// <summary>数据库列 <c>processed_at</c></summary>
    [JsonPropertyName("processedAt")]
    [GoOmitEmpty]
    public DateTime? ProcessedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentOrder</c>，数据库表 <c>payment_orders</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentOrder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>idempotency_key</c>（maxLength=120）</summary>
    [JsonPropertyName("idempotencyKey")]
    public string IdempotencyKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchant_order_no</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>product_id</c>（maxLength=36）</summary>
    [JsonPropertyName("productId")]
    public string ProductID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>product_name</c>（maxLength=120）</summary>
    [JsonPropertyName("productName")]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_id</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>plugin_id</c>（maxLength=120）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>plugin_version</c>（maxLength=40）</summary>
    [JsonPropertyName("pluginVersion")]
    public string PluginVersion { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_config_id</c>（maxLength=36）</summary>
    [JsonPropertyName("providerConfigId")]
    public string ProviderConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_config_version</c>（maxLength=64）</summary>
    [JsonPropertyName("providerConfigVersion")]
    public long ProviderConfigVersion { get; set; }

    /// <summary>数据库列 <c>amount_fen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>currency</c>（maxLength=8）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>credits_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("creditsMicrocredits")]
    public long CreditsMicrocredits { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_trade_no</c>（maxLength=96）</summary>
    [JsonPropertyName("providerTradeNo")]
    [GoOmitEmpty]
    public string? ProviderTradeNo { get; set; }

    /// <summary>数据库列 <c>provider_status</c>（maxLength=40）</summary>
    [JsonPropertyName("providerStatus")]
    [GoOmitEmpty]
    public string ProviderStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkout_mode</c>（maxLength=24）</summary>
    [JsonPropertyName("checkoutMode")]
    [GoOmitEmpty]
    public string CheckoutMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkout_value</c></summary>
    [JsonIgnore]
    public string CheckoutValue { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkout_expires_at</c></summary>
    [JsonPropertyName("checkoutExpiresAt")]
    [GoOmitEmpty]
    public DateTime? CheckoutExpiresAt { get; set; }

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>provider_paid_at</c></summary>
    [JsonPropertyName("providerPaidAt")]
    [GoOmitEmpty]
    public DateTime? ProviderPaidAt { get; set; }

    /// <summary>数据库列 <c>credited_at</c></summary>
    [JsonPropertyName("creditedAt")]
    [GoOmitEmpty]
    public DateTime? CreditedAt { get; set; }

    /// <summary>数据库列 <c>closed_at</c></summary>
    [JsonPropertyName("closedAt")]
    [GoOmitEmpty]
    public DateTime? ClosedAt { get; set; }

    /// <summary>数据库列 <c>last_queried_at</c></summary>
    [JsonPropertyName("lastQueriedAt")]
    [GoOmitEmpty]
    public DateTime? LastQueriedAt { get; set; }

    /// <summary>数据库列 <c>last_error</c>（maxLength=1000）</summary>
    [JsonPropertyName("lastError")]
    [GoOmitEmpty]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentProviderConfig</c>，数据库表 <c>payment_provider_configs</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentProviderConfig
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_id</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>plugin_id</c>（maxLength=120）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>plugin_version</c>（maxLength=40）</summary>
    [JsonPropertyName("pluginVersion")]
    public string PluginVersion { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>close_after_minutes</c>（maxLength=64）</summary>
    [JsonPropertyName("closeAfterMinutes")]
    public long CloseAfterMinutes { get; set; }

    /// <summary>数据库列 <c>config_cipher</c></summary>
    [JsonIgnore]
    public string ConfigCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>config_digest</c>（maxLength=64）</summary>
    [JsonPropertyName("configDigest")]
    public string ConfigDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentReconciliationItem</c>，数据库表 <c>payment_reconciliation_items</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentReconciliationItem
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>run_id</c>（maxLength=36）</summary>
    [JsonPropertyName("runId")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_id</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payment_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchant_order_no</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_trade_no</c>（maxLength=96）</summary>
    [JsonPropertyName("providerTradeNo")]
    [GoOmitEmpty]
    public string ProviderTradeNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amount_fen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>currency</c>（maxLength=8）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>result</c>（maxLength=48）</summary>
    [JsonPropertyName("result")]
    public string Result { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolved</c></summary>
    [JsonPropertyName("resolved")]
    public bool Resolved { get; set; }

    /// <summary>数据库列 <c>detail</c>（maxLength=1000）</summary>
    [JsonPropertyName("detail")]
    [GoOmitEmpty]
    public string Detail { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentReconciliationRun</c>，数据库表 <c>payment_reconciliation_runs</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentReconciliationRun
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_id</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>config_id</c>（maxLength=36）</summary>
    [JsonPropertyName("configId")]
    public string ConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bill_date</c>（maxLength=10）</summary>
    [JsonPropertyName("billDate")]
    public string BillDate { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>total_items</c>（maxLength=64）</summary>
    [JsonPropertyName("totalItems")]
    public long TotalItems { get; set; }

    /// <summary>数据库列 <c>match_items</c>（maxLength=64）</summary>
    [JsonPropertyName("matchItems")]
    public long MatchItems { get; set; }

    /// <summary>数据库列 <c>recovered_items</c>（maxLength=64）</summary>
    [JsonPropertyName("recoveredItems")]
    public long RecoveredItems { get; set; }

    /// <summary>数据库列 <c>error_items</c>（maxLength=64）</summary>
    [JsonPropertyName("errorItems")]
    public long ErrorItems { get; set; }

    /// <summary>数据库列 <c>error</c>（maxLength=1000）</summary>
    [JsonPropertyName("error")]
    [GoOmitEmpty]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_by</c>（maxLength=36）</summary>
    [JsonPropertyName("startedBy")]
    [GoOmitEmpty]
    public string StartedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime StartedAt { get; set; }

    /// <summary>数据库列 <c>completed_at</c></summary>
    [JsonPropertyName("completedAt")]
    [GoOmitEmpty]
    public DateTime? CompletedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>TopupProduct</c>，数据库表 <c>topup_products</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class TopupProduct
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    [GoOmitEmpty]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amount_fen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>credits_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("creditsMicrocredits")]
    public long CreditsMicrocredits { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>sort_order</c>（maxLength=64）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>updated_by</c>（maxLength=36）</summary>
    [JsonPropertyName("updatedBy")]
    public string UpdatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
