// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AuthVerification</c>，数据库表 <c>auth_verifications</c>。
/// 源文件：internal/model/models_notifications.go
/// </summary>
public class AuthVerification
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>token_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>purpose</c>（maxLength=24）</summary>
    [JsonPropertyName("")]
    public string Purpose { get; set; } = string.Empty;

    /// <summary>数据库列 <c>method</c>（maxLength=24）</summary>
    [JsonPropertyName("")]
    public string Method { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>email</c>（maxLength=160）</summary>
    [JsonPropertyName("")]
    public string Email { get; set; } = string.Empty;

    /// <summary>数据库列 <c>phone</c>（maxLength=24）</summary>
    [JsonPropertyName("")]
    public string Phone { get; set; } = string.Empty;

    /// <summary>数据库列 <c>email_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public string EmailHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>phone_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public string PhoneHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>policy_hash</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public string PolicyHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>ready</c></summary>
    [JsonPropertyName("")]
    public bool Ready { get; set; }

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>used_at</c></summary>
    [JsonPropertyName("")]
    public DateTime? UsedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>NotificationQuota</c>，数据库表 <c>notification_quota</c>。
/// 源文件：internal/model/models_notifications.go
/// </summary>
public class NotificationQuota
{
    /// <summary>数据库列 <c>key</c>（maxLength=180，主键）</summary>
    [JsonPropertyName("")]
    public string Key { get; set; } = string.Empty;

    /// <summary>数据库列 <c>count</c>（maxLength=64）</summary>
    [JsonPropertyName("")]
    public long Count { get; set; }

    /// <summary>数据库列 <c>next_at</c></summary>
    [JsonPropertyName("")]
    public DateTime NextAt { get; set; }

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("")]
    public DateTime ExpiresAt { get; set; }
}

/// <summary>
/// 对应 Go <c>SMSChannel</c>，数据库表 <c>sms_channels</c>。
/// 源文件：internal/model/models_notifications.go
/// </summary>
public class SMSChannel
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=80）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=32）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>priority</c>（maxLength=64）</summary>
    [JsonPropertyName("priority")]
    public long Priority { get; set; }

    /// <summary>数据库列 <c>daily_limit</c>（maxLength=64）</summary>
    [JsonPropertyName("dailyLimit")]
    public long DailyLimit { get; set; }

    /// <summary>数据库列 <c>sign_name</c>（maxLength=80）</summary>
    [JsonPropertyName("signName")]
    public string SignName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>app_id</c>（maxLength=80）</summary>
    [JsonPropertyName("appId")]
    public string AppID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>credentials</c></summary>
    [JsonIgnore]
    public string Credentials { get; set; } = string.Empty;

    /// <summary>数据库列 <c>templates_json</c></summary>
    [JsonIgnore]
    public string TemplatesJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>数据库列 <c>deleted_at</c></summary>
    [JsonIgnore]
    public DateTime? DeletedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>SMSRecord</c>，数据库表 <c>sms_records</c>。
/// 源文件：internal/model/models_notifications.go
/// </summary>
public class SMSRecord
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_name</c>（maxLength=80）</summary>
    [JsonPropertyName("channelName")]
    public string ChannelName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=32）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>purpose</c>（maxLength=24）</summary>
    [JsonPropertyName("purpose")]
    public string Purpose { get; set; } = string.Empty;

    /// <summary>数据库列 <c>masked_phone</c>（maxLength=32）</summary>
    [JsonPropertyName("maskedPhone")]
    public string MaskedPhone { get; set; } = string.Empty;

    /// <summary>数据库列 <c>target_hash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string TargetHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>state</c>（maxLength=24）</summary>
    [JsonPropertyName("state")]
    public string State { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_id</c>（maxLength=160）</summary>
    [JsonPropertyName("requestId")]
    public string RequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>message_id</c>（maxLength=160）</summary>
    [JsonPropertyName("messageId")]
    public string MessageID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error_code</c>（maxLength=160）</summary>
    [JsonPropertyName("errorCode")]
    public string ErrorCode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>duration_ms</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMS { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
