// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>IDSequence</c>，数据库表 <c>idSequences</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class IDSequence
{
    /// <summary>数据库列 <c>name</c>（maxLength=40，主键）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>value</c>（maxLength=64）</summary>
    [JsonPropertyName("value")]
    public long Value { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModelRevision</c>，数据库表 <c>logicalModelRevisions</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModelRevision
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logicalModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelId")]
    public string LogicalModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>capabilitySpecJson</c></summary>
    [JsonIgnore]
    public string CapabilitySpecJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>defaultOptionsJson</c></summary>
    [JsonIgnore]
    public string DefaultOptionsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModelRoute</c>，数据库表 <c>logicalModelRoutes</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModelRoute
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logicalModelRevisionId</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelRevisionId")]
    public string LogicalModelRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>priority</c>（maxLength=64）</summary>
    [JsonPropertyName("priority")]
    public long Priority { get; set; }

    /// <summary>数据库列 <c>weight</c>（maxLength=64）</summary>
    [JsonPropertyName("weight")]
    public long Weight { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModel</c>，数据库表 <c>logicalModels</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModel
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>code</c>（maxLength=80）</summary>
    [JsonPropertyName("code")]
    public string Code { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>icon</c>（maxLength=80）</summary>
    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>sortOrder</c>（maxLength=64）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>revisionSequence</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long RevisionSequence { get; set; }

    /// <summary>数据库列 <c>activeRevisionId</c>（maxLength=36）</summary>
    [JsonPropertyName("activeRevisionId")]
    public string ActiveRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceChannelModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("sourceChannelModelId")]
    [GoOmitEmpty]
    public string SourceChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pricePolicy</c>（maxLength=24）</summary>
    [JsonPropertyName("pricePolicy")]
    public string PricePolicy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billingMode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>inputPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputPriceMicrocredits")]
    public long InputPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>outputPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputPriceMicrocredits")]
    public long OutputPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cachedPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedPriceMicrocredits")]
    public long CachedPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>legacyModelIdsJson</c></summary>
    [JsonIgnore]
    public string LegacyModelIDsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>archivedAt</c></summary>
    [JsonIgnore]
    public DateTime? ArchivedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>RouteAttempt</c>，数据库表 <c>routeAttempts</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class RouteAttempt
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>routeRun</c>（maxLength=64）</summary>
    [JsonPropertyName("routeRun")]
    public long RouteRun { get; set; }

    /// <summary>数据库列 <c>attemptNumber</c>（maxLength=64）</summary>
    [JsonPropertyName("attemptNumber")]
    public long AttemptNumber { get; set; }

    /// <summary>数据库列 <c>logicalModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelId")]
    public string LogicalModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logicalModelRevisionId</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelRevisionId")]
    public string LogicalModelRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>routeId</c>（maxLength=36）</summary>
    [JsonPropertyName("routeId")]
    public string RouteID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>dispatchState</c>（maxLength=32）</summary>
    [JsonPropertyName("dispatchState")]
    public string DispatchState { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerRequestId</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>failureCode</c>（maxLength=80）</summary>
    [JsonPropertyName("failureCode")]
    public string FailureCode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>failureMessage</c>（maxLength=1000）</summary>
    [JsonPropertyName("failureMessage")]
    public string FailureMessage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startedAt</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime StartedAt { get; set; }

    /// <summary>数据库列 <c>completedAt</c></summary>
    [JsonPropertyName("completedAt")]
    public DateTime? CompletedAt { get; set; }
}
