// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>IDSequence</c>，数据库表 <c>id_sequences</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class IDSequence
{
    /// <summary>数据库列 <c>name</c>（maxLength=40，主键）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>value</c>（maxLength=64）</summary>
    [JsonPropertyName("value")]
    public long Value { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModelRevision</c>，数据库表 <c>logical_model_revisions</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModelRevision
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logical_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelId")]
    public string LogicalModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>capability_spec_json</c></summary>
    [JsonIgnore]
    public string CapabilitySpecJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>default_options_json</c></summary>
    [JsonIgnore]
    public string DefaultOptionsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModelRoute</c>，数据库表 <c>logical_model_routes</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModelRoute
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logical_model_revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelRevisionId")]
    public string LogicalModelRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>priority</c>（maxLength=64）</summary>
    [JsonPropertyName("priority")]
    public long Priority { get; set; }

    /// <summary>数据库列 <c>weight</c>（maxLength=64）</summary>
    [JsonPropertyName("weight")]
    public long Weight { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>LogicalModel</c>，数据库表 <c>logical_models</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class LogicalModel
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>code</c>（maxLength=80）</summary>
    [JsonPropertyName("code")]
    public string Code { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>icon</c>（maxLength=80）</summary>
    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>sort_order</c>（maxLength=64）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>revision_sequence</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long RevisionSequence { get; set; }

    /// <summary>数据库列 <c>active_revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("activeRevisionId")]
    public string ActiveRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source_channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("sourceChannelModelId")]
    [GoOmitEmpty]
    public string SourceChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>price_policy</c>（maxLength=24）</summary>
    [JsonPropertyName("pricePolicy")]
    public string PricePolicy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billing_mode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>input_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputPriceMicrocredits")]
    public long InputPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>output_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputPriceMicrocredits")]
    public long OutputPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cached_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedPriceMicrocredits")]
    public long CachedPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>legacy_model_ids_json</c></summary>
    [JsonIgnore]
    public string LegacyModelIDsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>archived_at</c></summary>
    [JsonIgnore]
    public DateTime? ArchivedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>RouteAttempt</c>，数据库表 <c>route_attempts</c>。
/// 源文件：internal/model/models_logical_model.go
/// </summary>
public class RouteAttempt
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>route_run</c>（maxLength=64）</summary>
    [JsonPropertyName("routeRun")]
    public long RouteRun { get; set; }

    /// <summary>数据库列 <c>attempt_number</c>（maxLength=64）</summary>
    [JsonPropertyName("attemptNumber")]
    public long AttemptNumber { get; set; }

    /// <summary>数据库列 <c>logical_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelId")]
    public string LogicalModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>logical_model_revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("logicalModelRevisionId")]
    public string LogicalModelRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>route_id</c>（maxLength=36）</summary>
    [JsonPropertyName("routeId")]
    public string RouteID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>dispatch_state</c>（maxLength=32）</summary>
    [JsonPropertyName("dispatchState")]
    public string DispatchState { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_request_id</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>failure_code</c>（maxLength=80）</summary>
    [JsonPropertyName("failureCode")]
    public string FailureCode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>failure_message</c>（maxLength=1000）</summary>
    [JsonPropertyName("failureMessage")]
    public string FailureMessage { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime StartedAt { get; set; }

    /// <summary>数据库列 <c>completed_at</c></summary>
    [JsonPropertyName("completedAt")]
    public DateTime? CompletedAt { get; set; }
}
