// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>PluginPlatformState</c>，数据库表 <c>plugin_platform_states</c>。
/// 源文件：internal/model/models_plugin.go
/// </summary>
public class PluginPlatformState
{
    /// <summary>数据库列 <c>plugin_id</c>（maxLength=120，主键）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>available</c></summary>
    [JsonPropertyName("available")]
    public bool Available { get; set; }

    /// <summary>数据库列 <c>updated_by</c>（maxLength=36）</summary>
    [JsonPropertyName("updatedBy")]
    public string UpdatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserPluginState</c>，数据库表 <c>user_plugin_states</c>。
/// 源文件：internal/model/models_plugin.go
/// </summary>
public class UserPluginState
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>plugin_id</c>（maxLength=120）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
