// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>CanvasSnapshotResource</c>，数据库表 <c>canvas_snapshot_resources</c>。
/// 源文件：internal/model/models_canvas_history.go
/// </summary>
public class CanvasSnapshotResource
{
    /// <summary>数据库列 <c>snapshot_id</c>（maxLength=36，主键）</summary>
    [JsonIgnore]
    public string SnapshotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resource_id</c>（maxLength=36，主键）</summary>
    [JsonIgnore]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonIgnore]
    public string? Resource { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasSnapshot</c>，数据库表 <c>canvas_snapshots</c>。
/// 源文件：internal/model/models_canvas_history.go
/// </summary>
public class CanvasSnapshot
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80，not null）</summary>
    [JsonPropertyName("canvasId")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36，not null）</summary>
    [JsonIgnore]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>node_count</c>（maxLength=64）</summary>
    [JsonPropertyName("nodeCount")]
    public long NodeCount { get; set; }

    /// <summary>数据库列 <c>connection_count</c>（maxLength=64）</summary>
    [JsonPropertyName("connectionCount")]
    public long ConnectionCount { get; set; }

    /// <summary>数据库列 <c>payload_bytes</c>（maxLength=64）</summary>
    [JsonPropertyName("payloadBytes")]
    public long PayloadBytes { get; set; }

    /// <summary>数据库列 <c>payload_json</c>（not null）</summary>
    [JsonIgnore]
    public string PayloadJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>reason</c>（maxLength=24）</summary>
    [JsonPropertyName("reason")]
    public string Reason { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content_updated_at</c></summary>
    [JsonPropertyName("contentUpdatedAt")]
    public DateTime ContentUpdatedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c>（not null）</summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}
