// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>BillingOrder</c>，数据库表 <c>billingOrders</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class BillingOrder
{
    /// <summary>数据库列 <c>costConfigured</c>（not null）</summary>
    [JsonIgnore]
    public bool CostConfigured { get; set; }

    /// <summary>数据库列 <c>costUnitPriceMicrocredits</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostUnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>costInputTokenPriceMicrocredits</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostInputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>costOutputTokenPriceMicrocredits</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostOutputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>costCachedTokenPriceMicrocredits</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostCachedTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>costBillingMode</c>（maxLength=32，not null）</summary>
    [JsonIgnore]
    public string CostBillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>costQuantity</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostQuantity { get; set; }

    /// <summary>数据库列 <c>costVideoFormulaTokens</c>（maxLength=64，not null）</summary>
    [JsonIgnore]
    public long CostVideoFormulaTokens { get; set; }

    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>idempotencyKey</c>（maxLength=160）</summary>
    [JsonPropertyName("idempotencyKey")]
    public string IdempotencyKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelModelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>priceTierId</c>（maxLength=36）</summary>
    [JsonPropertyName("priceTierId")]
    [GoOmitEmpty]
    public string PriceTierID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>priceTierVersion</c>（maxLength=64）</summary>
    [JsonPropertyName("priceTierVersion")]
    public long PriceTierVersion { get; set; }

    /// <summary>数据库列 <c>priceSelectorJson</c></summary>
    [JsonIgnore]
    public string PriceSelectorJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scene</c>（maxLength=80）</summary>
    [JsonPropertyName("scene")]
    public string Scene { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billingMode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>priceVersion</c>（maxLength=64）</summary>
    [JsonPropertyName("priceVersion")]
    public long PriceVersion { get; set; }

    /// <summary>数据库列 <c>unitPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>multiplierBasisPoints</c>（maxLength=64）</summary>
    [JsonPropertyName("multiplierBasisPoints")]
    public long MultiplierBasisPoints { get; set; }

    /// <summary>数据库列 <c>quantity</c>（maxLength=64）</summary>
    [JsonPropertyName("quantity")]
    public long Quantity { get; set; }

    /// <summary>数据库列 <c>amountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>reservedAmountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedAmountMicrocredits")]
    public long ReservedAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>chargeLimitSet</c>（not null）</summary>
    [JsonPropertyName("chargeLimitSet")]
    [GoOmitEmpty]
    public bool ChargeLimitSet { get; set; }

    /// <summary>数据库列 <c>chargeLimitMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("chargeLimitMicrocredits")]
    [GoOmitEmpty]
    public long ChargeLimitMicrocredits { get; set; }

    /// <summary>数据库列 <c>actualAmountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("actualAmountMicrocredits")]
    public long ActualAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>refundedAmountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("refundedAmountMicrocredits")]
    public long RefundedAmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>inputTokenPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokenPriceMicrocredits")]
    public long InputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>outputTokenPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokenPriceMicrocredits")]
    public long OutputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cachedTokenPriceMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokenPriceMicrocredits")]
    public long CachedTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>inputTokens</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokens")]
    public long InputTokens { get; set; }

    /// <summary>数据库列 <c>outputTokens</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokens")]
    public long OutputTokens { get; set; }

    /// <summary>数据库列 <c>cachedTokens</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokens")]
    public long CachedTokens { get; set; }

    /// <summary>数据库列 <c>videoFormulaTokens</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("videoFormulaTokens")]
    public long VideoFormulaTokens { get; set; }

    /// <summary>数据库列 <c>usageSource</c>（maxLength=32，not null）</summary>
    [JsonPropertyName("usageSource")]
    [GoOmitEmpty]
    public string UsageSource { get; set; } = string.Empty;

    /// <summary>数据库列 <c>usageAvailable</c></summary>
    [JsonPropertyName("usageAvailable")]
    public bool UsageAvailable { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerRequestId</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    [GoOmitEmpty]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c>（maxLength=1000）</summary>
    [JsonPropertyName("error")]
    [GoOmitEmpty]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolvedBy</c>（maxLength=36）</summary>
    [JsonPropertyName("resolvedBy")]
    [GoOmitEmpty]
    public string ResolvedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolutionNote</c>（maxLength=500）</summary>
    [JsonPropertyName("resolutionNote")]
    [GoOmitEmpty]
    public string ResolutionNote { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startedAt</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime? StartedAt { get; set; }

    /// <summary>数据库列 <c>settledAt</c></summary>
    [JsonPropertyName("settledAt")]
    public DateTime? SettledAt { get; set; }

    /// <summary>数据库列 <c>refundedAt</c></summary>
    [JsonPropertyName("refundedAt")]
    public DateTime? RefundedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CreditAccount</c>，数据库表 <c>creditAccounts</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class CreditAccount
{
    /// <summary>数据库列 <c>userId</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>availableMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableMicrocredits")]
    public long AvailableMicrocredits { get; set; }

    /// <summary>数据库列 <c>reservedMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedMicrocredits")]
    public long ReservedMicrocredits { get; set; }

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CreditLedgerEntry</c>，数据库表 <c>creditLedgerEntries</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class CreditLedgerEntry
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=32）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>availableDeltaMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableDeltaMicrocredits")]
    public long AvailableDeltaMicrocredits { get; set; }

    /// <summary>数据库列 <c>reservedDeltaMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedDeltaMicrocredits")]
    public long ReservedDeltaMicrocredits { get; set; }

    /// <summary>数据库列 <c>availableAfterMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("availableAfterMicrocredits")]
    public long AvailableAfterMicrocredits { get; set; }

    /// <summary>数据库列 <c>reservedAfterMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("reservedAfterMicrocredits")]
    public long ReservedAfterMicrocredits { get; set; }

    /// <summary>数据库列 <c>billingOrderId</c>（maxLength=36）</summary>
    [JsonPropertyName("billingOrderId")]
    [GoOmitEmpty]
    public string BillingOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>paymentOrderId</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeemCodeId</c>（maxLength=36）</summary>
    [JsonPropertyName("redeemCodeId")]
    [GoOmitEmpty]
    public string RedeemCodeID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>actorUserId</c>（maxLength=36）</summary>
    [JsonPropertyName("actorUserId")]
    [GoOmitEmpty]
    public string ActorUserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    [GoOmitEmpty]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    [GoOmitEmpty]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scene</c>（maxLength=80）</summary>
    [JsonPropertyName("scene")]
    [GoOmitEmpty]
    public string Scene { get; set; } = string.Empty;

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    [GoOmitEmpty]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>referenceKey</c>（maxLength=180）</summary>
    [JsonPropertyName("referenceKey")]
    [GoOmitEmpty]
    public string? ReferenceKey { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ModelPricing</c>，数据库表 <c>modelPricings</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class ModelPricing
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channelId</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>currency</c>（maxLength=12）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>inputPerMillionMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("inputPerMillionMicros")]
    public long InputPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>outputPerMillionMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("outputPerMillionMicros")]
    public long OutputPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>cachedPerMillionMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedPerMillionMicros")]
    public long CachedPerMillionMicros { get; set; }

    /// <summary>数据库列 <c>perRequestMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("perRequestMicros")]
    public long PerRequestMicros { get; set; }

    /// <summary>数据库列 <c>perMediaMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("perMediaMicros")]
    public long PerMediaMicros { get; set; }

    /// <summary>数据库列 <c>perVideoSecondMicros</c>（maxLength=64）</summary>
    [JsonPropertyName("perVideoSecondMicros")]
    public long PerVideoSecondMicros { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>RedeemBatch</c>，数据库表 <c>redeemBatches</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class RedeemBatch
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>count</c>（maxLength=64）</summary>
    [JsonPropertyName("count")]
    public long Count { get; set; }

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codesCipher</c></summary>
    [JsonIgnore]
    public string CodesCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("availableCount")]
    public long AvailableCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("redeemedCount")]
    public long RedeemedCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("disabledCount")]
    public long DisabledCount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("expiredCount")]
    public long ExpiredCount { get; set; }
}

/// <summary>
/// 对应 Go <c>RedeemCode</c>，数据库表 <c>redeemCodes</c>。
/// 源文件：internal/model/models_finance.go
/// </summary>
public class RedeemCode
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>batchId</c>（maxLength=36）</summary>
    [JsonPropertyName("batchId")]
    public string BatchID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codeHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string CodeHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>codeSuffix</c>（maxLength=4）</summary>
    [JsonPropertyName("codeSuffix")]
    public string CodeSuffix { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amountMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("amountMicrocredits")]
    public long AmountMicrocredits { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeemedBy</c>（maxLength=36）</summary>
    [JsonPropertyName("redeemedBy")]
    [GoOmitEmpty]
    public string RedeemedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>redeemedAt</c></summary>
    [JsonPropertyName("redeemedAt")]
    public DateTime? RedeemedAt { get; set; }

    /// <summary>数据库列 <c>redeemedIp</c>（maxLength=64）</summary>
    [JsonPropertyName("redeemedIp")]
    [GoOmitEmpty]
    public string RedeemedIP { get; set; } = string.Empty;

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
