// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AgentLesson</c>，数据库表 <c>agent_lessons</c>。
/// 源文件：internal/model/models_agent_lesson.go
/// </summary>
public class AgentLesson
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>topic</c>（maxLength=120）</summary>
    [JsonPropertyName("topic")]
    public string Topic { get; set; } = string.Empty;

    /// <summary>数据库列 <c>category</c>（maxLength=32）</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>数据库列 <c>situation</c></summary>
    [JsonPropertyName("situation")]
    public string Situation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>lesson</c></summary>
    [JsonPropertyName("lesson")]
    public string Lesson { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source</c>（maxLength=200）</summary>
    [JsonPropertyName("source")]
    public string Source { get; set; } = string.Empty;

    /// <summary>数据库列 <c>steps_json</c></summary>
    [JsonIgnore]
    public string StepsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=16）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>author_user_id</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string AuthorUserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>hits</c>（maxLength=64）</summary>
    [JsonPropertyName("hits")]
    public long Hits { get; set; }

    /// <summary>数据库列 <c>injected</c>（maxLength=64）</summary>
    [JsonPropertyName("injected")]
    public long Injected { get; set; }

    /// <summary>数据库列 <c>last_verified_at</c></summary>
    [JsonPropertyName("lastVerifiedAt")]
    [GoOmitEmpty]
    public DateTime? LastVerifiedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
