// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AnnouncementImageDraft</c>，数据库表 <c>announcement_image_drafts</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AnnouncementImageDraft
{
    /// <summary>数据库列 <c>resource_id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("resourceId")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Announcement</c>，数据库表 <c>announcements</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Announcement
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=120）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>image_resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("imageResourceId")]
    [GoOmitEmpty]
    public string ImageResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>level</c>（maxLength=24）</summary>
    [JsonPropertyName("level")]
    public string Level { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pinned</c></summary>
    [JsonPropertyName("pinned")]
    public bool Pinned { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>published_at</c></summary>
    [JsonPropertyName("publishedAt")]
    public DateTime PublishedAt { get; set; }

    /// <summary>数据库列 <c>closed_at</c></summary>
    [JsonPropertyName("closedAt")]
    public DateTime? ClosedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("imageUrl")]
    [GoOmitEmpty]
    public string ImageURL { get; set; } = string.Empty;
}

/// <summary>
/// 对应 Go <c>AssetFolder</c>，数据库表 <c>asset_folders</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetFolder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=80）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name_key</c>（maxLength=80）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>AssetRepresentation</c>，数据库表 <c>asset_representations</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetRepresentation
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>asset_version_id</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    [GoOmitEmpty]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>media_type</c>（maxLength=24）</summary>
    [JsonPropertyName("mediaType")]
    public string MediaType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>metadata_json</c></summary>
    [JsonPropertyName("metadataJson")]
    public string MetadataJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>AssetVersion</c>，数据库表 <c>asset_versions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetVersion
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>asset_id</c>（maxLength=80）</summary>
    [JsonPropertyName("assetId")]
    public string AssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>definition_json</c></summary>
    [JsonPropertyName("definitionJson")]
    public string DefinitionJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>prompt</c></summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Asset</c>，数据库表 <c>assets</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Asset
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>folder_id</c>（maxLength=36）</summary>
    [JsonPropertyName("folderId")]
    [GoOmitEmpty]
    public string FolderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>category</c>（maxLength=32）</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>primary_version_id</c>（maxLength=36）</summary>
    [JsonPropertyName("primaryVersionId")]
    [GoOmitEmpty]
    public string PrimaryVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload_json</c></summary>
    [JsonPropertyName("payloadJson")]
    public string PayloadJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasProject</c>，数据库表 <c>canvas_projects</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasProject
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    [GoOmitEmpty]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payload_json</c></summary>
    [JsonPropertyName("payloadJson")]
    public string PayloadJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasShare</c>，数据库表 <c>canvas_shares</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasShare
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=80）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>token_hash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>token_cipher</c></summary>
    [JsonIgnore]
    public string TokenCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>expires_at</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasUnitLink</c>，数据库表 <c>canvas_unit_links</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasUnitLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CharacterVoiceBinding</c>，数据库表 <c>character_voice_bindings</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CharacterVoiceBinding
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>asset_version_id</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>voice_profile_id</c>（maxLength=36）</summary>
    [JsonPropertyName("voiceProfileId")]
    public string VoiceProfileID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>instructions</c></summary>
    [JsonPropertyName("instructions")]
    public string Instructions { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProductionTaskLink</c>，数据库表 <c>production_task_links</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProductionTaskLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvas_id</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    [GoOmitEmpty]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_id</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    [GoOmitEmpty]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflow_step_id</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowStepId")]
    [GoOmitEmpty]
    public string WorkflowStepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>artifact_type</c>（maxLength=40）</summary>
    [JsonPropertyName("artifactType")]
    [GoOmitEmpty]
    public string ArtifactType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetCandidate</c>，数据库表 <c>project_asset_candidates</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetCandidate
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_id</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    [GoOmitEmpty]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name_key</c>（maxLength=240）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>category</c>（maxLength=32）</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source</c>（maxLength=48）</summary>
    [JsonPropertyName("source")]
    [GoOmitEmpty]
    public string Source { get; set; } = string.Empty;

    /// <summary>数据库列 <c>details_json</c></summary>
    [JsonPropertyName("detailsJson")]
    public string DetailsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolved_asset_id</c>（maxLength=80）</summary>
    [JsonPropertyName("resolvedAssetId")]
    [GoOmitEmpty]
    public string ResolvedAssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetFolder</c>，数据库表 <c>project_asset_folders</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetFolder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>parent_id</c>（maxLength=36）</summary>
    [JsonPropertyName("parentId")]
    [GoOmitEmpty]
    public string ParentID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name_key</c>（maxLength=240）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>style</c>（maxLength=24）</summary>
    [JsonPropertyName("style")]
    public string Style { get; set; } = string.Empty;

    /// <summary>数据库列 <c>theme</c>（maxLength=24）</summary>
    [JsonPropertyName("theme")]
    public string Theme { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetLink</c>，数据库表 <c>project_asset_links</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>asset_id</c>（maxLength=80）</summary>
    [JsonPropertyName("assetId")]
    public string AssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>folder_id</c>（maxLength=36）</summary>
    [JsonPropertyName("folderId")]
    [GoOmitEmpty]
    public string FolderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectUnit</c>，数据库表 <c>project_units</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectUnit
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>parent_id</c>（maxLength=36）</summary>
    [JsonPropertyName("parentId")]
    [GoOmitEmpty]
    public string ParentID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source_text</c></summary>
    [JsonPropertyName("sourceText")]
    public string SourceText { get; set; } = string.Empty;

    /// <summary>数据库列 <c>word_count</c>（maxLength=64）</summary>
    [JsonPropertyName("wordCount")]
    public long WordCount { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Project</c>，数据库表 <c>projects</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Project
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=32）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>aspect_ratio</c>（maxLength=16）</summary>
    [JsonPropertyName("aspectRatio")]
    public string AspectRatio { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source_type</c>（maxLength=32）</summary>
    [JsonPropertyName("sourceType")]
    public string SourceType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c></summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cover_resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("coverResourceId")]
    [GoOmitEmpty]
    public string CoverResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>style_preset_id</c>（maxLength=64）</summary>
    [JsonPropertyName("stylePresetId")]
    public string StylePresetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>style_profile_json</c></summary>
    [JsonPropertyName("styleProfileJson")]
    public string StyleProfileJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>default_image_model</c>（maxLength=500）</summary>
    [JsonPropertyName("defaultImageModel")]
    [GoOmitEmpty]
    public string DefaultImageModel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>default_video_model</c>（maxLength=500）</summary>
    [JsonPropertyName("defaultVideoModel")]
    [GoOmitEmpty]
    public string DefaultVideoModel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PromptTemplate</c>，数据库表 <c>prompt_templates</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class PromptTemplate
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>output_type</c>（maxLength=24）</summary>
    [JsonPropertyName("outputType")]
    public string OutputType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ResourceDeletionJob</c>，数据库表 <c>resource_deletion_jobs</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ResourceDeletionJob
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=24）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>endpoint</c></summary>
    [JsonPropertyName("endpoint")]
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bucket</c>（maxLength=160）</summary>
    [JsonPropertyName("bucket")]
    public string Bucket { get; set; } = string.Empty;

    /// <summary>数据库列 <c>storage_setting_id</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string StorageSettingID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>object_key</c></summary>
    [JsonPropertyName("objectKey")]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>last_error</c></summary>
    [JsonPropertyName("lastError")]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>next_attempt_at</c></summary>
    [JsonPropertyName("nextAttemptAt")]
    public DateTime NextAttemptAt { get; set; }

    /// <summary>数据库列 <c>lease_owner</c>（maxLength=120）</summary>
    [JsonIgnore]
    public string LeaseOwner { get; set; } = string.Empty;

    /// <summary>数据库列 <c>lease_expires_at</c></summary>
    [JsonIgnore]
    public DateTime? LeaseExpiresAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Resource</c>，数据库表 <c>resources</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Resource
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=24）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>endpoint</c></summary>
    [JsonPropertyName("endpoint")]
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bucket</c>（maxLength=160）</summary>
    [JsonPropertyName("bucket")]
    public string Bucket { get; set; } = string.Empty;

    /// <summary>数据库列 <c>storage_setting_id</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string StorageSettingID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>object_key</c></summary>
    [JsonPropertyName("objectKey")]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>public_url</c></summary>
    [JsonPropertyName("publicUrl")]
    public string PublicURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mime_type</c>（maxLength=120）</summary>
    [JsonPropertyName("mimeType")]
    public string MimeType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>size</c>（maxLength=64）</summary>
    [JsonPropertyName("size")]
    public long Size { get; set; }

    /// <summary>数据库列 <c>width</c>（maxLength=64）</summary>
    [JsonPropertyName("width")]
    public long Width { get; set; }

    /// <summary>数据库列 <c>height</c>（maxLength=64）</summary>
    [JsonPropertyName("height")]
    public long Height { get; set; }

    /// <summary>数据库列 <c>duration_ms</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>e_tag</c>（maxLength=160）</summary>
    [JsonPropertyName("etag")]
    public string ETag { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playback_status</c>（maxLength=24）</summary>
    [JsonPropertyName("playbackStatus")]
    public string PlaybackStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playback_object_key</c></summary>
    [JsonPropertyName("playbackObjectKey")]
    public string PlaybackObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playback_error</c></summary>
    [JsonPropertyName("playbackError")]
    public string PlaybackError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>upload_key</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string? UploadKey { get; set; }

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotArtifact</c>，数据库表 <c>shot_artifacts</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotArtifact
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_id</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("revisionId")]
    [GoOmitEmpty]
    public string RevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=40）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    [GoOmitEmpty]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>selected</c></summary>
    [JsonPropertyName("selected")]
    public bool Selected { get; set; }

    /// <summary>数据库列 <c>metadata_json</c></summary>
    [JsonPropertyName("metadataJson")]
    public string MetadataJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotAssetReference</c>，数据库表 <c>shot_asset_references</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotAssetReference
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_id</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>asset_version_id</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotRevision</c>，数据库表 <c>shot_revisions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotRevision
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_id</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>plot_description</c></summary>
    [JsonPropertyName("plotDescription")]
    public string PlotDescription { get; set; } = string.Empty;

    /// <summary>数据库列 <c>action</c></summary>
    [JsonPropertyName("action")]
    public string Action { get; set; } = string.Empty;

    /// <summary>数据库列 <c>dialogue</c></summary>
    [JsonPropertyName("dialogue")]
    public string Dialogue { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shot_size</c>（maxLength=80）</summary>
    [JsonPropertyName("shotSize")]
    public string ShotSize { get; set; } = string.Empty;

    /// <summary>数据库列 <c>camera_angle</c>（maxLength=80）</summary>
    [JsonPropertyName("cameraAngle")]
    public string CameraAngle { get; set; } = string.Empty;

    /// <summary>数据库列 <c>camera_movement</c>（maxLength=120）</summary>
    [JsonPropertyName("cameraMovement")]
    public string CameraMovement { get; set; } = string.Empty;

    /// <summary>数据库列 <c>duration_ms</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>image_prompt</c></summary>
    [JsonPropertyName("imagePrompt")]
    public string ImagePrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>video_prompt</c></summary>
    [JsonPropertyName("videoPrompt")]
    public string VideoPrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>negative_prompt</c></summary>
    [JsonPropertyName("negativePrompt")]
    public string NegativePrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>continuity_notes</c></summary>
    [JsonPropertyName("continuityNotes")]
    public string ContinuityNotes { get; set; } = string.Empty;

    /// <summary>数据库列 <c>action_beats_json</c></summary>
    [JsonPropertyName("actionBeatsJson")]
    public string ActionBeatsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_by</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    [GoOmitEmpty]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Shot</c>，数据库表 <c>shots</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Shot
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>current_revision_id</c>（maxLength=36）</summary>
    [JsonPropertyName("currentRevisionId")]
    [GoOmitEmpty]
    public string CurrentRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c></summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>duration_ms</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>StyleProfile</c>，数据库表 <c>style_profiles</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class StyleProfile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cover_url</c></summary>
    [JsonPropertyName("coverUrl")]
    public string CoverURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tags_json</c></summary>
    [JsonPropertyName("tagsJson")]
    public string TagsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>profile_json</c></summary>
    [JsonPropertyName("profileJson")]
    public string ProfileJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>favorite</c></summary>
    [JsonPropertyName("favorite")]
    public bool Favorite { get; set; }

    /// <summary>数据库列 <c>last_used_at</c></summary>
    [JsonPropertyName("lastUsedAt")]
    [GoOmitEmpty]
    public DateTime? LastUsedAt { get; set; }

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserAnnouncementRead</c>，数据库表 <c>user_announcement_reads</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class UserAnnouncementRead
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>announcement_id</c>（maxLength=36）</summary>
    [JsonPropertyName("announcementId")]
    public string AnnouncementID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>read_at</c></summary>
    [JsonPropertyName("readAt")]
    public DateTime ReadAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserPromptCustomization</c>，数据库表 <c>user_prompt_customizations</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class UserPromptCustomization
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mode</c>（maxLength=24）</summary>
    [JsonPropertyName("mode")]
    public string Mode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>base_template_id</c>（maxLength=36）</summary>
    [JsonPropertyName("baseTemplateId")]
    public string BaseTemplateID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>VoiceProfile</c>，数据库表 <c>voice_profiles</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class VoiceProfile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=48）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>voice_key</c>（maxLength=160）</summary>
    [JsonPropertyName("voiceKey")]
    public string VoiceKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>language</c>（maxLength=80）</summary>
    [JsonPropertyName("language")]
    public string Language { get; set; } = string.Empty;

    /// <summary>数据库列 <c>timbre</c>（maxLength=240）</summary>
    [JsonPropertyName("timbre")]
    public string Timbre { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sample_resource_id</c>（maxLength=36）</summary>
    [JsonPropertyName("sampleResourceId")]
    [GoOmitEmpty]
    public string SampleResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>compatible_models_json</c></summary>
    [JsonPropertyName("compatibleModelsJson")]
    public string CompatibleModelsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowInstance</c>，数据库表 <c>workflow_instances</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowInstance
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>project_id</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_id</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>template_version_id</c>（maxLength=36）</summary>
    [JsonPropertyName("templateVersionId")]
    public string TemplateVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scope</c>（maxLength=24）</summary>
    [JsonPropertyName("scope")]
    public string Scope { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowStepInstance</c>，数据库表 <c>workflow_step_instances</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowStepInstance
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflow_instance_id</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowInstanceId")]
    public string WorkflowInstanceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>step_key</c>（maxLength=80）</summary>
    [JsonPropertyName("stepKey")]
    public string StepKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>input_json</c></summary>
    [JsonPropertyName("inputJson")]
    public string InputJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>output_json</c></summary>
    [JsonPropertyName("outputJson")]
    public string OutputJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime? StartedAt { get; set; }

    /// <summary>数据库列 <c>completed_at</c></summary>
    [JsonPropertyName("completedAt")]
    public DateTime? CompletedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowStepTask</c>，数据库表 <c>workflow_step_tasks</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowStepTask
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflow_step_id</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowStepId")]
    public string WorkflowStepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowTemplateVersion</c>，数据库表 <c>workflow_template_versions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowTemplateVersion
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>template_key</c>（maxLength=80）</summary>
    [JsonPropertyName("templateKey")]
    public string TemplateKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>definition_json</c></summary>
    [JsonPropertyName("definitionJson")]
    public string DefinitionJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}
