// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>ApiCallLog</c>，数据库表 <c>api_call_logs</c>。
/// 源文件：internal/model/models_channel.go
/// </summary>
public class ApiCallLog
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>trace_id</c>（maxLength=96）</summary>
    [JsonPropertyName("traceId")]
    [GoOmitEmpty]
    public string TraceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_id</c>（maxLength=96）</summary>
    [JsonPropertyName("requestId")]
    [GoOmitEmpty]
    public string RequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>task_id</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billing_order_id</c>（maxLength=36）</summary>
    [JsonPropertyName("billingOrderId")]
    [GoOmitEmpty]
    public string BillingOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source</c>（maxLength=64）</summary>
    [JsonPropertyName("source")]
    public string Source { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_kind</c>（maxLength=24）</summary>
    [JsonPropertyName("requestKind")]
    public string RequestKind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billable</c></summary>
    [JsonPropertyName("billable")]
    public bool Billable { get; set; }

    /// <summary>数据库列 <c>api_format</c>（maxLength=24）</summary>
    [JsonPropertyName("apiFormat")]
    public string APIFormat { get; set; } = string.Empty;

    /// <summary>数据库列 <c>method</c>（maxLength=16）</summary>
    [JsonPropertyName("method")]
    public string Method { get; set; } = string.Empty;

    /// <summary>数据库列 <c>path</c></summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model</c>（maxLength=120）</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status_code</c>（maxLength=64）</summary>
    [JsonPropertyName("statusCode")]
    public long StatusCode { get; set; }

    /// <summary>数据库列 <c>duration_ms</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>poll_count</c>（maxLength=64）</summary>
    [JsonPropertyName("pollCount")]
    public long PollCount { get; set; }

    /// <summary>数据库列 <c>provider_status</c>（maxLength=32）</summary>
    [JsonPropertyName("providerStatus")]
    [GoOmitEmpty]
    public string ProviderStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>input_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokens")]
    public long InputTokens { get; set; }

    /// <summary>数据库列 <c>output_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokens")]
    public long OutputTokens { get; set; }

    /// <summary>数据库列 <c>cached_tokens</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokens")]
    public long CachedTokens { get; set; }

    /// <summary>数据库列 <c>usage_available</c></summary>
    [JsonPropertyName("usageAvailable")]
    public bool UsageAvailable { get; set; }

    /// <summary>数据库列 <c>media_count</c>（maxLength=64）</summary>
    [JsonPropertyName("mediaCount")]
    public long MediaCount { get; set; }

    /// <summary>数据库列 <c>video_seconds</c>（maxLength=64）</summary>
    [JsonPropertyName("videoSeconds")]
    public long VideoSeconds { get; set; }

    /// <summary>数据库列 <c>provider_request_id</c>（maxLength=160）</summary>
    [JsonPropertyName("providerRequestId")]
    public string ProviderRequestID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>estimated_cost_micros</c>（maxLength=64）</summary>
    [JsonPropertyName("estimatedCostMicros")]
    public long EstimatedCostMicros { get; set; }

    /// <summary>数据库列 <c>cost_available</c></summary>
    [JsonPropertyName("costAvailable")]
    public bool CostAvailable { get; set; }

    /// <summary>数据库列 <c>currency</c>（maxLength=12）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error_code</c>（maxLength=80）</summary>
    [JsonPropertyName("errorCode")]
    [GoOmitEmpty]
    public string ErrorCode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>concurrency_limit</c>（maxLength=64）</summary>
    [JsonPropertyName("concurrencyLimit")]
    public long ConcurrencyLimit { get; set; }

    /// <summary>数据库列 <c>upstream_url</c></summary>
    [JsonPropertyName("upstreamUrl")]
    public string UpstreamURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_content_type</c>（maxLength=160）</summary>
    [JsonPropertyName("requestContentType")]
    [GoOmitEmpty]
    public string RequestContentType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>request_body</c></summary>
    [JsonPropertyName("requestBody")]
    [GoOmitEmpty]
    public string RequestBody { get; set; } = string.Empty;

    /// <summary>数据库列 <c>response_body</c></summary>
    [JsonPropertyName("responseBody")]
    [GoOmitEmpty]
    public string ResponseBody { get; set; } = string.Empty;

    /// <summary>数据库列 <c>started_at</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime StartedAt { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("userDisplayName")]
    [GoOmitEmpty]
    public string UserDisplayName { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("userAccount")]
    [GoOmitEmpty]
    public string UserAccount { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("channelName")]
    public string ChannelName { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("taskStatus")]
    [GoOmitEmpty]
    public string TaskStatus { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("billingStatus")]
    [GoOmitEmpty]
    public string BillingStatus { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("billingAmountMicrocredits")]
    public long BillingAmount { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("billingAvailable")]
    public bool BillingAvailable { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("mediaPreviewUrl")]
    [GoOmitEmpty]
    public string MediaPreviewURL { get; set; } = string.Empty;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("mediaPreviewKind")]
    [GoOmitEmpty]
    public string MediaPreviewKind { get; set; } = string.Empty;
}

/// <summary>
/// 对应 Go <c>ChannelModelPriceTier</c>，数据库表 <c>channel_model_price_tiers</c>。
/// 源文件：internal/model/models_channel.go
/// </summary>
public class ChannelModelPriceTier
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_model_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelModelId")]
    public string ChannelModelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>selector_key</c>（maxLength=500，not null）</summary>
    [JsonPropertyName("selectorKey")]
    public string SelectorKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>selector_json</c>（not null）</summary>
    [JsonIgnore]
    public string SelectorJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolution</c>（maxLength=24，not null）</summary>
    [JsonPropertyName("resolution")]
    public string Resolution { get; set; } = string.Empty;

    /// <summary>数据库列 <c>video_seconds</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("videoSeconds")]
    public long VideoSeconds { get; set; }

    /// <summary>数据库列 <c>provider_model_key</c>（maxLength=120）</summary>
    [JsonPropertyName("providerModelKey")]
    public string ProviderModelKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billing_mode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>input_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokenPriceMicrocredits")]
    public long InputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>output_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokenPriceMicrocredits")]
    public long OutputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cached_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokenPriceMicrocredits")]
    public long CachedTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>price_configured</c></summary>
    [JsonPropertyName("priceConfigured")]
    public bool PriceConfigured { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>price_version</c>（maxLength=64）</summary>
    [JsonPropertyName("priceVersion")]
    public long PriceVersion { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>数据库列 <c>deleted_at</c></summary>
    [JsonIgnore]
    public DateTime? DeletedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("selector")]
    [GoOmitEmpty]
    public Dictionary<string, string> Selector { get; set; } = null!;
}

/// <summary>
/// 对应 Go <c>ChannelModel</c>，数据库表 <c>channel_models</c>。
/// 源文件：internal/model/models_channel.go
/// </summary>
public class ChannelModel
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>channel_id</c>（maxLength=36）</summary>
    [JsonPropertyName("channelId")]
    public string ChannelID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>model_key</c>（maxLength=120）</summary>
    [JsonPropertyName("modelKey")]
    public string ModelKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider_model_key</c>（maxLength=120）</summary>
    [JsonPropertyName("providerModelKey")]
    public string ProviderModelKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>display_name</c>（maxLength=160）</summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sort_order</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>icon</c>（maxLength=80）</summary>
    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability</c>（maxLength=32）</summary>
    [JsonPropertyName("capability")]
    public string Capability { get; set; } = string.Empty;

    /// <summary>数据库列 <c>protocol</c>（maxLength=32）</summary>
    [JsonPropertyName("protocol")]
    public string Protocol { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billing_mode</c>（maxLength=32）</summary>
    [JsonPropertyName("billingMode")]
    public string BillingMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unit_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("unitPriceMicrocredits")]
    public long UnitPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>input_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("inputTokenPriceMicrocredits")]
    public long InputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>output_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("outputTokenPriceMicrocredits")]
    public long OutputTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>cached_token_price_microcredits</c>（maxLength=64）</summary>
    [JsonPropertyName("cachedTokenPriceMicrocredits")]
    public long CachedTokenPriceMicrocredits { get; set; }

    /// <summary>数据库列 <c>price_configured</c></summary>
    [JsonPropertyName("priceConfigured")]
    public bool PriceConfigured { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>price_version</c>（maxLength=64）</summary>
    [JsonPropertyName("priceVersion")]
    public long PriceVersion { get; set; }

    /// <summary>数据库列 <c>capability_config_json</c></summary>
    [JsonIgnore]
    public string CapabilityConfigJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>capability_version</c>（maxLength=64）</summary>
    [JsonPropertyName("capabilityVersion")]
    public long CapabilityVersion { get; set; }

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>数据库列 <c>deleted_at</c></summary>
    [JsonIgnore]
    public DateTime? DeletedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("capabilityConfig")]
    [GoOmitEmpty]
    public Dictionary<string, JsonElement> CapabilityConfig { get; set; } = null!;

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("priceTiers")]
    public List<ChannelModelPriceTier> PriceTiers { get; set; } = null!;
}

/// <summary>
/// 对应 Go <c>ModelChannel</c>，数据库表 <c>model_channels</c>。
/// 源文件：internal/model/models_channel.go
/// </summary>
public class ModelChannel
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scope</c>（maxLength=24）</summary>
    [JsonPropertyName("scope")]
    public string Scope { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>name</c>（maxLength=80）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>public_alias</c>（maxLength=80，not null）</summary>
    [JsonPropertyName("publicAlias")]
    public string PublicAlias { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sort_order</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>base_url</c></summary>
    [JsonPropertyName("baseUrl")]
    public string BaseURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>api_key</c></summary>
    [JsonIgnore]
    public string APIKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>secret_key</c></summary>
    [JsonIgnore]
    public string SecretKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>api_format</c>（maxLength=24）</summary>
    [JsonPropertyName("apiFormat")]
    public string APIFormat { get; set; } = string.Empty;

    /// <summary>数据库列 <c>concurrency_limit</c>（maxLength=64）</summary>
    [JsonPropertyName("concurrencyLimit")]
    public long ConcurrencyLimit { get; set; }

    /// <summary>数据库列 <c>models_json</c></summary>
    [JsonPropertyName("modelsJson")]
    public string ModelsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>retired_models_json</c></summary>
    [JsonIgnore]
    public string RetiredModelsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>headers_json</c></summary>
    [JsonIgnore]
    public string HeadersJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updated_at</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>数据库列 <c>deleted_at</c></summary>
    [JsonIgnore]
    public DateTime? DeletedAt { get; set; }
}
