// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AnnouncementImageDraft</c>，数据库表 <c>announcementImageDrafts</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AnnouncementImageDraft
{
    /// <summary>数据库列 <c>resourceId</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("resourceId")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Announcement</c>，数据库表 <c>announcements</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Announcement
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=120）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>imageResourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("imageResourceId")]
    [GoOmitEmpty]
    public string ImageResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>level</c>（maxLength=24）</summary>
    [JsonPropertyName("level")]
    public string Level { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pinned</c></summary>
    [JsonPropertyName("pinned")]
    public bool Pinned { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>publishedAt</c></summary>
    [JsonPropertyName("publishedAt")]
    public DateTime PublishedAt { get; set; }

    /// <summary>数据库列 <c>closedAt</c></summary>
    [JsonPropertyName("closedAt")]
    public DateTime? ClosedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("imageUrl")]
    [GoOmitEmpty]
    public string ImageURL { get; set; } = string.Empty;
}

/// <summary>
/// 对应 Go <c>AssetFolder</c>，数据库表 <c>assetFolders</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetFolder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=80）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nameKey</c>（maxLength=80）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>AssetRepresentation</c>，数据库表 <c>assetRepresentations</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetRepresentation
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    [GoOmitEmpty]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mediaType</c>（maxLength=24）</summary>
    [JsonPropertyName("mediaType")]
    public string MediaType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>metadataJson</c></summary>
    [JsonPropertyName("metadataJson")]
    public string MetadataJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>AssetVersion</c>，数据库表 <c>assetVersions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class AssetVersion
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetId</c>（maxLength=80）</summary>
    [JsonPropertyName("assetId")]
    public string AssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>definitionJson</c></summary>
    [JsonPropertyName("definitionJson")]
    public string DefinitionJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>prompt</c></summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>note</c>（maxLength=500）</summary>
    [JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Asset</c>，数据库表 <c>assets</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Asset
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>folderId</c>（maxLength=36）</summary>
    [JsonPropertyName("folderId")]
    [GoOmitEmpty]
    public string FolderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>category</c>（maxLength=32）</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>primaryVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("primaryVersionId")]
    [GoOmitEmpty]
    public string PrimaryVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payloadJson</c></summary>
    [JsonPropertyName("payloadJson")]
    public string PayloadJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>BannerAnnouncement</c>，数据库表 <c>bannerAnnouncements</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class BannerAnnouncement
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=120）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>titleRuns</c></summary>
    [JsonIgnore]
    public string TitleRunsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>noticeType</c>（maxLength=24）</summary>
    [JsonPropertyName("noticeType")]
    public string NoticeType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>link</c>（maxLength=500）</summary>
    [JsonPropertyName("link")]
    public string Link { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startsAt</c></summary>
    [JsonPropertyName("startsAt")]
    [GoOmitEmpty]
    public DateTime? StartsAt { get; set; }

    /// <summary>数据库列 <c>endsAt</c></summary>
    [JsonPropertyName("endsAt")]
    [GoOmitEmpty]
    public DateTime? EndsAt { get; set; }

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    /// <summary>瞬态字段（Go <c>gorm:"-"</c>）：不建列，但参与 JSON 序列化。</summary>
    [JsonPropertyName("titleRuns")]
    [GoOmitEmpty]
    public List<BannerTitleRun> TitleRuns { get; set; } = null!;
}

/// <summary>
/// 对应 Go <c>CanvasProject</c>，数据库表 <c>canvasProjects</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasProject
{
    /// <summary>数据库列 <c>id</c>（maxLength=80，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    [GoOmitEmpty]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payloadJson</c></summary>
    [JsonPropertyName("payloadJson")]
    public string PayloadJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64，not null）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasShare</c>，数据库表 <c>canvasShares</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasShare
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=80）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tokenHash</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tokenCipher</c></summary>
    [JsonIgnore]
    public string TokenCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CanvasUnitLink</c>，数据库表 <c>canvasUnitLinks</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CanvasUnitLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvasId</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>CharacterVoiceBinding</c>，数据库表 <c>characterVoiceBindings</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class CharacterVoiceBinding
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>voiceProfileId</c>（maxLength=36）</summary>
    [JsonPropertyName("voiceProfileId")]
    public string VoiceProfileID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>instructions</c></summary>
    [JsonPropertyName("instructions")]
    public string Instructions { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProductionTaskLink</c>，数据库表 <c>productionTaskLinks</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProductionTaskLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>canvasId</c>（maxLength=80）</summary>
    [JsonPropertyName("canvasId")]
    [GoOmitEmpty]
    public string CanvasID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotId</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    [GoOmitEmpty]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflowStepId</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowStepId")]
    [GoOmitEmpty]
    public string WorkflowStepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>artifactType</c>（maxLength=40）</summary>
    [JsonPropertyName("artifactType")]
    [GoOmitEmpty]
    public string ArtifactType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetCandidate</c>，数据库表 <c>projectAssetCandidates</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetCandidate
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotId</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    [GoOmitEmpty]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nameKey</c>（maxLength=240）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>category</c>（maxLength=32）</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=32）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>source</c>（maxLength=48）</summary>
    [JsonPropertyName("source")]
    [GoOmitEmpty]
    public string Source { get; set; } = string.Empty;

    /// <summary>数据库列 <c>detailsJson</c></summary>
    [JsonPropertyName("detailsJson")]
    public string DetailsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolvedAssetId</c>（maxLength=80）</summary>
    [JsonPropertyName("resolvedAssetId")]
    [GoOmitEmpty]
    public string ResolvedAssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetFolder</c>，数据库表 <c>projectAssetFolders</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetFolder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>parentId</c>（maxLength=36）</summary>
    [JsonPropertyName("parentId")]
    [GoOmitEmpty]
    public string ParentID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nameKey</c>（maxLength=240）</summary>
    [JsonIgnore]
    public string NameKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>style</c>（maxLength=24）</summary>
    [JsonPropertyName("style")]
    public string Style { get; set; } = string.Empty;

    /// <summary>数据库列 <c>theme</c>（maxLength=24）</summary>
    [JsonPropertyName("theme")]
    public string Theme { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectAssetLink</c>，数据库表 <c>projectAssetLinks</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectAssetLink
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetId</c>（maxLength=80）</summary>
    [JsonPropertyName("assetId")]
    public string AssetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>folderId</c>（maxLength=36）</summary>
    [JsonPropertyName("folderId")]
    [GoOmitEmpty]
    public string FolderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ProjectUnit</c>，数据库表 <c>projectUnits</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ProjectUnit
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>parentId</c>（maxLength=36）</summary>
    [JsonPropertyName("parentId")]
    [GoOmitEmpty]
    public string ParentID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceText</c></summary>
    [JsonPropertyName("sourceText")]
    public string SourceText { get; set; } = string.Empty;

    /// <summary>数据库列 <c>wordCount</c>（maxLength=64）</summary>
    [JsonPropertyName("wordCount")]
    public long WordCount { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Project</c>，数据库表 <c>projects</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Project
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=240）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=32）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>aspectRatio</c>（maxLength=16）</summary>
    [JsonPropertyName("aspectRatio")]
    public string AspectRatio { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sourceType</c>（maxLength=32）</summary>
    [JsonPropertyName("sourceType")]
    public string SourceType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c></summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>coverResourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("coverResourceId")]
    [GoOmitEmpty]
    public string CoverResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stylePresetId</c>（maxLength=64）</summary>
    [JsonPropertyName("stylePresetId")]
    public string StylePresetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>styleProfileJson</c></summary>
    [JsonPropertyName("styleProfileJson")]
    public string StyleProfileJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>defaultImageModel</c>（maxLength=500）</summary>
    [JsonPropertyName("defaultImageModel")]
    [GoOmitEmpty]
    public string DefaultImageModel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>defaultVideoModel</c>（maxLength=500）</summary>
    [JsonPropertyName("defaultVideoModel")]
    [GoOmitEmpty]
    public string DefaultVideoModel { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PromptTemplate</c>，数据库表 <c>promptTemplates</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class PromptTemplate
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>outputType</c>（maxLength=24）</summary>
    [JsonPropertyName("outputType")]
    public string OutputType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ResourceDeletionJob</c>，数据库表 <c>resourceDeletionJobs</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ResourceDeletionJob
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=24）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>endpoint</c></summary>
    [JsonPropertyName("endpoint")]
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bucket</c>（maxLength=160）</summary>
    [JsonPropertyName("bucket")]
    public string Bucket { get; set; } = string.Empty;

    /// <summary>数据库列 <c>storageSettingId</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string StorageSettingID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>objectKey</c></summary>
    [JsonPropertyName("objectKey")]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>lastError</c></summary>
    [JsonPropertyName("lastError")]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nextAttemptAt</c></summary>
    [JsonPropertyName("nextAttemptAt")]
    public DateTime NextAttemptAt { get; set; }

    /// <summary>数据库列 <c>leaseOwner</c>（maxLength=120）</summary>
    [JsonIgnore]
    public string LeaseOwner { get; set; } = string.Empty;

    /// <summary>数据库列 <c>leaseExpiresAt</c></summary>
    [JsonIgnore]
    public DateTime? LeaseExpiresAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Resource</c>，数据库表 <c>resources</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Resource
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>kind</c>（maxLength=24）</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=24）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>endpoint</c></summary>
    [JsonPropertyName("endpoint")]
    public string Endpoint { get; set; } = string.Empty;

    /// <summary>数据库列 <c>bucket</c>（maxLength=160）</summary>
    [JsonPropertyName("bucket")]
    public string Bucket { get; set; } = string.Empty;

    /// <summary>数据库列 <c>storageSettingId</c>（maxLength=36）</summary>
    [JsonIgnore]
    public string StorageSettingID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>objectKey</c></summary>
    [JsonPropertyName("objectKey")]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>publicUrl</c></summary>
    [JsonPropertyName("publicUrl")]
    public string PublicURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mimeType</c>（maxLength=120）</summary>
    [JsonPropertyName("mimeType")]
    public string MimeType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>size</c>（maxLength=64）</summary>
    [JsonPropertyName("size")]
    public long Size { get; set; }

    /// <summary>数据库列 <c>width</c>（maxLength=64）</summary>
    [JsonPropertyName("width")]
    public long Width { get; set; }

    /// <summary>数据库列 <c>height</c>（maxLength=64）</summary>
    [JsonPropertyName("height")]
    public long Height { get; set; }

    /// <summary>数据库列 <c>durationMs</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>eTag</c>（maxLength=160）</summary>
    [JsonPropertyName("etag")]
    public string ETag { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playbackStatus</c>（maxLength=24）</summary>
    [JsonPropertyName("playbackStatus")]
    public string PlaybackStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playbackObjectKey</c></summary>
    [JsonPropertyName("playbackObjectKey")]
    public string PlaybackObjectKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>playbackError</c></summary>
    [JsonPropertyName("playbackError")]
    public string PlaybackError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>uploadKey</c>（maxLength=64）</summary>
    [JsonIgnore]
    public string? UploadKey { get; set; }

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotArtifact</c>，数据库表 <c>shotArtifacts</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotArtifact
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotId</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revisionId</c>（maxLength=36）</summary>
    [JsonPropertyName("revisionId")]
    [GoOmitEmpty]
    public string RevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    [GoOmitEmpty]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>type</c>（maxLength=40）</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>resourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("resourceId")]
    [GoOmitEmpty]
    public string ResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>selected</c></summary>
    [JsonPropertyName("selected")]
    public bool Selected { get; set; }

    /// <summary>数据库列 <c>metadataJson</c></summary>
    [JsonPropertyName("metadataJson")]
    public string MetadataJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotAssetReference</c>，数据库表 <c>shotAssetReferences</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotAssetReference
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotId</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>assetVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("assetVersionId")]
    public string AssetVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>role</c>（maxLength=32）</summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>ShotRevision</c>，数据库表 <c>shotRevisions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class ShotRevision
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotId</c>（maxLength=36）</summary>
    [JsonPropertyName("shotId")]
    public string ShotID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>plotDescription</c></summary>
    [JsonPropertyName("plotDescription")]
    public string PlotDescription { get; set; } = string.Empty;

    /// <summary>数据库列 <c>action</c></summary>
    [JsonPropertyName("action")]
    public string Action { get; set; } = string.Empty;

    /// <summary>数据库列 <c>dialogue</c></summary>
    [JsonPropertyName("dialogue")]
    public string Dialogue { get; set; } = string.Empty;

    /// <summary>数据库列 <c>shotSize</c>（maxLength=80）</summary>
    [JsonPropertyName("shotSize")]
    public string ShotSize { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cameraAngle</c>（maxLength=80）</summary>
    [JsonPropertyName("cameraAngle")]
    public string CameraAngle { get; set; } = string.Empty;

    /// <summary>数据库列 <c>cameraMovement</c>（maxLength=120）</summary>
    [JsonPropertyName("cameraMovement")]
    public string CameraMovement { get; set; } = string.Empty;

    /// <summary>数据库列 <c>durationMs</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>imagePrompt</c></summary>
    [JsonPropertyName("imagePrompt")]
    public string ImagePrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>videoPrompt</c></summary>
    [JsonPropertyName("videoPrompt")]
    public string VideoPrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>negativePrompt</c></summary>
    [JsonPropertyName("negativePrompt")]
    public string NegativePrompt { get; set; } = string.Empty;

    /// <summary>数据库列 <c>continuityNotes</c></summary>
    [JsonPropertyName("continuityNotes")]
    public string ContinuityNotes { get; set; } = string.Empty;

    /// <summary>数据库列 <c>actionBeatsJson</c></summary>
    [JsonPropertyName("actionBeatsJson")]
    public string ActionBeatsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    [GoOmitEmpty]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>Shot</c>，数据库表 <c>shots</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class Shot
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>currentRevisionId</c>（maxLength=36）</summary>
    [JsonPropertyName("currentRevisionId")]
    [GoOmitEmpty]
    public string CurrentRevisionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>title</c>（maxLength=240）</summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c></summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>durationMs</c>（maxLength=64）</summary>
    [JsonPropertyName("durationMs")]
    public long DurationMs { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>StyleProfile</c>，数据库表 <c>styleProfiles</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class StyleProfile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>coverUrl</c></summary>
    [JsonPropertyName("coverUrl")]
    public string CoverURL { get; set; } = string.Empty;

    /// <summary>数据库列 <c>tagsJson</c></summary>
    [JsonPropertyName("tagsJson")]
    public string TagsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>profileJson</c></summary>
    [JsonPropertyName("profileJson")]
    public string ProfileJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>favorite</c></summary>
    [JsonPropertyName("favorite")]
    public bool Favorite { get; set; }

    /// <summary>数据库列 <c>lastUsedAt</c></summary>
    [JsonPropertyName("lastUsedAt")]
    [GoOmitEmpty]
    public DateTime? LastUsedAt { get; set; }

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserAnnouncementRead</c>，数据库表 <c>userAnnouncementReads</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class UserAnnouncementRead
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>announcementId</c>（maxLength=36）</summary>
    [JsonPropertyName("announcementId")]
    public string AnnouncementID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>readAt</c></summary>
    [JsonPropertyName("readAt")]
    public DateTime ReadAt { get; set; }
}

/// <summary>
/// 对应 Go <c>UserPromptCustomization</c>，数据库表 <c>userPromptCustomizations</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class UserPromptCustomization
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>operation</c>（maxLength=64）</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; set; } = string.Empty;

    /// <summary>数据库列 <c>mode</c>（maxLength=24）</summary>
    [JsonPropertyName("mode")]
    public string Mode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>content</c></summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>数据库列 <c>baseTemplateId</c>（maxLength=36）</summary>
    [JsonPropertyName("baseTemplateId")]
    public string BaseTemplateID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>VoiceProfile</c>，数据库表 <c>voiceProfiles</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class VoiceProfile
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>provider</c>（maxLength=48）</summary>
    [JsonPropertyName("provider")]
    public string Provider { get; set; } = string.Empty;

    /// <summary>数据库列 <c>voiceKey</c>（maxLength=160）</summary>
    [JsonPropertyName("voiceKey")]
    public string VoiceKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>language</c>（maxLength=80）</summary>
    [JsonPropertyName("language")]
    public string Language { get; set; } = string.Empty;

    /// <summary>数据库列 <c>timbre</c>（maxLength=240）</summary>
    [JsonPropertyName("timbre")]
    public string Timbre { get; set; } = string.Empty;

    /// <summary>数据库列 <c>sampleResourceId</c>（maxLength=36）</summary>
    [JsonPropertyName("sampleResourceId")]
    [GoOmitEmpty]
    public string SampleResourceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>compatibleModelsJson</c></summary>
    [JsonPropertyName("compatibleModelsJson")]
    public string CompatibleModelsJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowInstance</c>，数据库表 <c>workflowInstances</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowInstance
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>projectId</c>（maxLength=36）</summary>
    [JsonPropertyName("projectId")]
    public string ProjectID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>unitId</c>（maxLength=36）</summary>
    [JsonPropertyName("unitId")]
    [GoOmitEmpty]
    public string UnitID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>templateVersionId</c>（maxLength=36）</summary>
    [JsonPropertyName("templateVersionId")]
    public string TemplateVersionID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>scope</c>（maxLength=24）</summary>
    [JsonPropertyName("scope")]
    public string Scope { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>revision</c>（maxLength=64）</summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowStepInstance</c>，数据库表 <c>workflowStepInstances</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowStepInstance
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflowInstanceId</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowInstanceId")]
    public string WorkflowInstanceID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>stepKey</c>（maxLength=80）</summary>
    [JsonPropertyName("stepKey")]
    public string StepKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>position</c>（maxLength=64）</summary>
    [JsonPropertyName("position")]
    public long Position { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>inputJson</c></summary>
    [JsonPropertyName("inputJson")]
    public string InputJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>outputJson</c></summary>
    [JsonPropertyName("outputJson")]
    public string OutputJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>error</c></summary>
    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startedAt</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime? StartedAt { get; set; }

    /// <summary>数据库列 <c>completedAt</c></summary>
    [JsonPropertyName("completedAt")]
    public DateTime? CompletedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowStepTask</c>，数据库表 <c>workflowStepTasks</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowStepTask
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>workflowStepId</c>（maxLength=36）</summary>
    [JsonPropertyName("workflowStepId")]
    public string WorkflowStepID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>taskId</c>（maxLength=36）</summary>
    [JsonPropertyName("taskId")]
    public string TaskID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>WorkflowTemplateVersion</c>，数据库表 <c>workflowTemplateVersions</c>。
/// 源文件：internal/model/models_project.go
/// </summary>
public class WorkflowTemplateVersion
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>templateKey</c>（maxLength=80）</summary>
    [JsonPropertyName("templateKey")]
    public string TemplateKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=160）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>definitionJson</c></summary>
    [JsonPropertyName("definitionJson")]
    public string DefinitionJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>BannerTitleRun</c>（辅助结构体，非独立数据表）。源文件：internal/model/models_project.go
/// </summary>
public class BannerTitleRun
{
    /// <summary>对应 Go <c>BannerTitleRun.Text</c>。</summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;

    /// <summary>对应 Go <c>BannerTitleRun.FontSize</c>。</summary>
    [JsonPropertyName("fontSize")]
    [GoOmitEmpty]
    public long? FontSize { get; set; }

    /// <summary>对应 Go <c>BannerTitleRun.FontWeight</c>。</summary>
    [JsonPropertyName("fontWeight")]
    [GoOmitEmpty]
    public long? FontWeight { get; set; }

    /// <summary>对应 Go <c>BannerTitleRun.FontFamily</c>。</summary>
    [JsonPropertyName("fontFamily")]
    [GoOmitEmpty]
    public string FontFamily { get; set; } = string.Empty;

    /// <summary>对应 Go <c>BannerTitleRun.Color</c>。</summary>
    [JsonPropertyName("color")]
    [GoOmitEmpty]
    public string Color { get; set; } = string.Empty;
}

