// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>AdminAuditEvent</c>，数据库表 <c>admin_audit_events</c>。
/// 源文件：internal/model/models.go
/// </summary>
public class AdminAuditEvent
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>actor_user_id</c>（maxLength=36）</summary>
    [JsonPropertyName("actorUserId")]
    public string ActorUserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>action</c>（maxLength=80）</summary>
    [JsonPropertyName("action")]
    public string Action { get; set; } = string.Empty;

    /// <summary>数据库列 <c>target_type</c>（maxLength=40）</summary>
    [JsonPropertyName("targetType")]
    public string TargetType { get; set; } = string.Empty;

    /// <summary>数据库列 <c>target_id</c>（maxLength=160）</summary>
    [JsonPropertyName("targetId")]
    public string TargetID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>summary</c>（maxLength=500）</summary>
    [JsonPropertyName("summary")]
    public string Summary { get; set; } = string.Empty;

    /// <summary>数据库列 <c>metadata_json</c></summary>
    [JsonPropertyName("metadataJson")]
    public string MetadataJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>created_at</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}
