// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>PaymentNotification</c>，数据库表 <c>paymentNotifications</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentNotification
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerId</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerEventId</c>（maxLength=160）</summary>
    [JsonPropertyName("providerEventId")]
    public string ProviderEventID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerConfigId</c>（maxLength=36）</summary>
    [JsonPropertyName("providerConfigId")]
    public string ProviderConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchantOrderNo</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    [GoOmitEmpty]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>paymentOrderId</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payloadDigest</c>（maxLength=64）</summary>
    [JsonPropertyName("payloadDigest")]
    public string PayloadDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>payloadCipher</c></summary>
    [JsonIgnore]
    public string PayloadCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>normalizedJson</c></summary>
    [JsonIgnore]
    public string NormalizedJSON { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>attempts</c>（maxLength=64）</summary>
    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    /// <summary>数据库列 <c>lastError</c>（maxLength=1000）</summary>
    [JsonPropertyName("lastError")]
    [GoOmitEmpty]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>nextAttemptAt</c></summary>
    [JsonPropertyName("nextAttemptAt")]
    public DateTime NextAttemptAt { get; set; }

    /// <summary>数据库列 <c>processedAt</c></summary>
    [JsonPropertyName("processedAt")]
    [GoOmitEmpty]
    public DateTime? ProcessedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentOrder</c>，数据库表 <c>paymentOrders</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentOrder
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>userId</c>（maxLength=36）</summary>
    [JsonPropertyName("userId")]
    public string UserID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>idempotencyKey</c>（maxLength=120）</summary>
    [JsonPropertyName("idempotencyKey")]
    public string IdempotencyKey { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchantOrderNo</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>productId</c>（maxLength=36）</summary>
    [JsonPropertyName("productId")]
    public string ProductID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>productName</c>（maxLength=120）</summary>
    [JsonPropertyName("productName")]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerId</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pluginId</c>（maxLength=120）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pluginVersion</c>（maxLength=40）</summary>
    [JsonPropertyName("pluginVersion")]
    public string PluginVersion { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerConfigId</c>（maxLength=36）</summary>
    [JsonPropertyName("providerConfigId")]
    public string ProviderConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerConfigVersion</c>（maxLength=64）</summary>
    [JsonPropertyName("providerConfigVersion")]
    public long ProviderConfigVersion { get; set; }

    /// <summary>数据库列 <c>amountFen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>currency</c>（maxLength=8）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>creditsMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("creditsMicrocredits")]
    public long CreditsMicrocredits { get; set; }

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerTradeNo</c>（maxLength=96）</summary>
    [JsonPropertyName("providerTradeNo")]
    [GoOmitEmpty]
    public string? ProviderTradeNo { get; set; }

    /// <summary>数据库列 <c>providerStatus</c>（maxLength=40）</summary>
    [JsonPropertyName("providerStatus")]
    [GoOmitEmpty]
    public string ProviderStatus { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkoutMode</c>（maxLength=24）</summary>
    [JsonPropertyName("checkoutMode")]
    [GoOmitEmpty]
    public string CheckoutMode { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkoutValue</c></summary>
    [JsonIgnore]
    public string CheckoutValue { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checkoutExpiresAt</c></summary>
    [JsonPropertyName("checkoutExpiresAt")]
    [GoOmitEmpty]
    public DateTime? CheckoutExpiresAt { get; set; }

    /// <summary>数据库列 <c>expiresAt</c></summary>
    [JsonPropertyName("expiresAt")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>数据库列 <c>providerPaidAt</c></summary>
    [JsonPropertyName("providerPaidAt")]
    [GoOmitEmpty]
    public DateTime? ProviderPaidAt { get; set; }

    /// <summary>数据库列 <c>creditedAt</c></summary>
    [JsonPropertyName("creditedAt")]
    [GoOmitEmpty]
    public DateTime? CreditedAt { get; set; }

    /// <summary>数据库列 <c>closedAt</c></summary>
    [JsonPropertyName("closedAt")]
    [GoOmitEmpty]
    public DateTime? ClosedAt { get; set; }

    /// <summary>数据库列 <c>lastQueriedAt</c></summary>
    [JsonPropertyName("lastQueriedAt")]
    [GoOmitEmpty]
    public DateTime? LastQueriedAt { get; set; }

    /// <summary>数据库列 <c>lastError</c>（maxLength=1000）</summary>
    [JsonPropertyName("lastError")]
    [GoOmitEmpty]
    public string LastError { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentProviderConfig</c>，数据库表 <c>paymentProviderConfigs</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentProviderConfig
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerId</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pluginId</c>（maxLength=120）</summary>
    [JsonPropertyName("pluginId")]
    public string PluginID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>pluginVersion</c>（maxLength=40）</summary>
    [JsonPropertyName("pluginVersion")]
    public string PluginVersion { get; set; } = string.Empty;

    /// <summary>数据库列 <c>version</c>（maxLength=64）</summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>closeAfterMinutes</c>（maxLength=64）</summary>
    [JsonPropertyName("closeAfterMinutes")]
    public long CloseAfterMinutes { get; set; }

    /// <summary>数据库列 <c>configCipher</c></summary>
    [JsonIgnore]
    public string ConfigCipher { get; set; } = string.Empty;

    /// <summary>数据库列 <c>configDigest</c>（maxLength=64）</summary>
    [JsonPropertyName("configDigest")]
    public string ConfigDigest { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentReconciliationItem</c>，数据库表 <c>paymentReconciliationItems</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentReconciliationItem
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>runId</c>（maxLength=36）</summary>
    [JsonPropertyName("runId")]
    public string RunID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerId</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>paymentOrderId</c>（maxLength=36）</summary>
    [JsonPropertyName("paymentOrderId")]
    [GoOmitEmpty]
    public string PaymentOrderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>merchantOrderNo</c>（maxLength=32）</summary>
    [JsonPropertyName("merchantOrderNo")]
    public string MerchantOrderNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerTradeNo</c>（maxLength=96）</summary>
    [JsonPropertyName("providerTradeNo")]
    [GoOmitEmpty]
    public string ProviderTradeNo { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amountFen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>currency</c>（maxLength=8）</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    /// <summary>数据库列 <c>result</c>（maxLength=48）</summary>
    [JsonPropertyName("result")]
    public string Result { get; set; } = string.Empty;

    /// <summary>数据库列 <c>resolved</c></summary>
    [JsonPropertyName("resolved")]
    public bool Resolved { get; set; }

    /// <summary>数据库列 <c>detail</c>（maxLength=1000）</summary>
    [JsonPropertyName("detail")]
    [GoOmitEmpty]
    public string Detail { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>PaymentReconciliationRun</c>，数据库表 <c>paymentReconciliationRuns</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class PaymentReconciliationRun
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>providerId</c>（maxLength=80）</summary>
    [JsonPropertyName("providerId")]
    public string ProviderID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>configId</c>（maxLength=36）</summary>
    [JsonPropertyName("configId")]
    public string ConfigID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>billDate</c>（maxLength=10）</summary>
    [JsonPropertyName("billDate")]
    public string BillDate { get; set; } = string.Empty;

    /// <summary>数据库列 <c>status</c>（maxLength=24）</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>数据库列 <c>totalItems</c>（maxLength=64）</summary>
    [JsonPropertyName("totalItems")]
    public long TotalItems { get; set; }

    /// <summary>数据库列 <c>matchItems</c>（maxLength=64）</summary>
    [JsonPropertyName("matchItems")]
    public long MatchItems { get; set; }

    /// <summary>数据库列 <c>recoveredItems</c>（maxLength=64）</summary>
    [JsonPropertyName("recoveredItems")]
    public long RecoveredItems { get; set; }

    /// <summary>数据库列 <c>errorItems</c>（maxLength=64）</summary>
    [JsonPropertyName("errorItems")]
    public long ErrorItems { get; set; }

    /// <summary>数据库列 <c>error</c>（maxLength=1000）</summary>
    [JsonPropertyName("error")]
    [GoOmitEmpty]
    public string Error { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startedBy</c>（maxLength=36）</summary>
    [JsonPropertyName("startedBy")]
    [GoOmitEmpty]
    public string StartedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>startedAt</c></summary>
    [JsonPropertyName("startedAt")]
    public DateTime StartedAt { get; set; }

    /// <summary>数据库列 <c>completedAt</c></summary>
    [JsonPropertyName("completedAt")]
    [GoOmitEmpty]
    public DateTime? CompletedAt { get; set; }

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}

/// <summary>
/// 对应 Go <c>TopupProduct</c>，数据库表 <c>topupProducts</c>。
/// 源文件：internal/model/models_payment.go
/// </summary>
public class TopupProduct
{
    /// <summary>数据库列 <c>id</c>（maxLength=36，主键）</summary>
    [JsonPropertyName("id")]
    public string ID { get; set; } = string.Empty;

    /// <summary>数据库列 <c>name</c>（maxLength=120）</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>description</c>（maxLength=500）</summary>
    [JsonPropertyName("description")]
    [GoOmitEmpty]
    public string Description { get; set; } = string.Empty;

    /// <summary>数据库列 <c>amountFen</c>（maxLength=64）</summary>
    [JsonPropertyName("amountFen")]
    public long AmountFen { get; set; }

    /// <summary>数据库列 <c>creditsMicrocredits</c>（maxLength=64）</summary>
    [JsonPropertyName("creditsMicrocredits")]
    public long CreditsMicrocredits { get; set; }

    /// <summary>数据库列 <c>enabled</c></summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }

    /// <summary>数据库列 <c>sortOrder</c>（maxLength=64）</summary>
    [JsonPropertyName("sortOrder")]
    public long SortOrder { get; set; }

    /// <summary>数据库列 <c>createdBy</c>（maxLength=36）</summary>
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>updatedBy</c>（maxLength=36）</summary>
    [JsonPropertyName("updatedBy")]
    public string UpdatedBy { get; set; } = string.Empty;

    /// <summary>数据库列 <c>createdAt</c></summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>数据库列 <c>updatedAt</c></summary>
    [JsonPropertyName("updatedAt")]
    public DateTime UpdatedAt { get; set; }
}
