// <auto-generated />
// 由 scripts/generate-entities.py 从 cmd/schema-dump 的权威导出生成，请勿手工编辑。
// 重新生成：cd backend && go run ./cmd/schema-dump > ../backend-dotnet/schema-dump.json
//           cd ../backend-dotnet && python scripts/generate-entities.py schema-dump.json
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenAICanvas.Domain.Serialization;

namespace OpenAICanvas.Domain.Entities;

/// <summary>
/// 对应 Go <c>schemaMigration</c>，数据库表 <c>schema_migrations</c>。
/// 源文件：internal/database/migrations.go
/// </summary>
public class SchemaMigration
{
    /// <summary>数据库列 <c>version</c>（maxLength=64，主键）</summary>
    [JsonPropertyName("")]
    public long Version { get; set; }

    /// <summary>数据库列 <c>name</c>（maxLength=160，not null）</summary>
    [JsonPropertyName("")]
    public string Name { get; set; } = string.Empty;

    /// <summary>数据库列 <c>checksum</c>（maxLength=96，not null）</summary>
    [JsonPropertyName("")]
    public string Checksum { get; set; } = string.Empty;

    /// <summary>数据库列 <c>applied_at</c>（not null）</summary>
    [JsonPropertyName("")]
    public DateTime AppliedAt { get; set; }
}
